app/db/migrate/00000000000000_update_table_permissions.rb
app/db/migrate/20240423000000_set_db_table_permissions.rb

In development, we may not have an "app" user and a "migrate" user.
Also, this removes a duplicate migration.

Fix table permission migration so it runs in development

---

infra/app/app-config/dev.tf
infra/app/app-config/env-config/environment-variables.tf
infra/project-config/networks.tf

The infra template makes this quite easy, fingers crossed.
After merging, I will run the commands listed in [https-support.md][1]
and [set-up-custom-domains.md][2].
Finishes FFS-878.
[1]: https://github.com/DSACMS/iv-cbv-payroll/blob/main/docs/infra/https-support.md
[2]: https://github.com/DSACMS/iv-cbv-payroll/blob/main/docs/infra/set-up-custom-domains.md

Enable HTTPS via AWS ACM and Route53

---

app/app/controllers/health_check_controller.rb
app/spec/controllers/health_check_controller_spec.rb

This changes the response to /health from a 200 OK with no body to being
a 200 OK with a JSON body similar to:
```
{ "status": "ok", "version": "abcdef0123..." }
```
This will help us verify which version of code has been deployed.

Add IMAGE_TAG to healthcheck

---

app/Dockerfile
app/app/controllers/health_check_controller.rb
app/bin/dev
app/config/initializers/wicked_pdf.rb
app/config/routes.rb

Addresses my own feedback from PR #43.
See detail in commit messages:
- **Don't copy wkhtmltopdf binary around**
- **Add PDF test rendering endpoint**
- **Fix bin/dev script to only remove pidfile if the process is dead**

Address feedback from PR #43

---

app/Gemfile

This gem doesn't work in production due to our readonly filesystem.
There, we install wkhtmltopdf via apt instead. So let's force it to be
used.

Use `wkhtmltopdf-binary` gem in dev/test only

---

infra/modules/email/main.tf

This is the last piece of DNS configuration on the AWS dashboard for the
domain. If this doesn't result in the domain being verified, I don't
know what will.

Add DMARC record for AWS SES domain

---

infra/modules/service/main.tf

We don't actually install wget inside the containers, so this
healthcheck was always failing and has been provisioning new containers
all the time. This may have been the source of some of our deployment
downtime.
It works:

Fix AWS ECS healthcheck by using `curl` instead of `wget`

---

Brewfile
bin/ecs-console
infra/app/app-config/dev.tf
infra/modules/service/main.tf

I want to look at our database in RDS to debug some strange behavior.
Thankfully, we already have [the configuration in place][1] to be able
to use ECS Exec to get me a shell in there. This commit enables the
configuration, and adds a helper script, so we can get a Rails console
in the demo environment running via:
```bash
bin/ecs-console
```
Also fixed/changed:
* Install `ngrok` correctly via Brew
* Install `awscli` and the necessary `session-manager-plugin`
* Revert `readonlyRootFilesystem` configuration to be dependent on
whether command execution is enabled
[1]: https://github.com/DSACMS/iv-cbv-payroll/blob/main/docs/infra/service-command-execution.md

Enable "ECS Exec" for debugging in AWS ECS

---

app/app/controllers/cbv_flows_controller.rb
app/config/locales/en.yml
app/spec/controllers/cbv_flows_controller_spec.rb

This is probably only an issue for development, while we have a CBV flow
in our session for development and then want to later test following a
CBV invite via tokenized link. The current behavior is that if there is
a CBV flow in the session, it will be prioritized over the tokenized
link.
But this seems a bit mistaken. If two people are applying for SNAP
one-after-the-other on the same device, we will want the second link to
work despite the presence of the first flow_id in the session.

Use CBV invite as higher priority than whatever's in session

---

infra/modules/network/main.tf
infra/modules/network/variables.tf
infra/networks/main.tf
infra/project-config/networks.tf

NAT Gateways are pricey, at $32/month, and also entail provisioning
an Elastic IP ($4/month). This isn't going to break the bank, but also,
it isn't necessary at all for our non-production environments since they
can tolerate an unlikely AWS AZ outage.
This commit adds the ability to pass through a `single_nat_gateway`
variable all the way to the `vpc` module, which supports sending all our
external traffic via a single NAT gateway.

Allow specifying `single_nat_gateway` in network_config

---

app/app/controllers/cbv_flow_invitations_controller.rb
app/config/locales/en.yml
app/spec/controllers/cbv_flow_invitations_controller_spec.rb

When there is a delivery error, let's catch it and give the user a
better error message.
In order to test this in development, you'll need to set
`config.action_mailer.raise_delivery_errors` to true. (It's true by
default in production.)
Finishes FFS-839.

Handle delivery error in CBV Flow Invitations Controller

---

app/app/services/pinwheel_service.rb
app/app/views/cbv_flows/_employer.html.erb
app/config/locales/en.yml
app/spec/controllers/api/pinwheel_controller_spec.rb
app/spec/services/pinwheel_service_spec.rb

For situations when Pinwheel doesn't return the employer matches, this
commit adds a button to the bottom of the employer search page (only
visible after a search is performed) that opens the default Pinwheel
modal.
https://github.com/DSACMS/iv-cbv-payroll/assets/129120/b2883c09-f2d2-4a7c-8454-583fe21601b7

Add "Search for Payroll Provider" button to employer search page

---

app/app/views/cbv_flows/_employer.html.erb
app/config/locales/en.yml

I had intended to do this in 0f06c10, but forgot to commit it. Let's
only show the "Employer not listed?" zero-state after a search is
performed.

Only show "Employer not listed?" after search

---

app/app/controllers/cbv/resets_controller.rb

I had accidentally broken this in 8b1a5c9 by converting it to a RESTful
route but not changing the controller method name to match. Thankfully
[a code review comment][1] drew my attention to this.
[1]: https://github.com/DSACMS/iv-cbv-payroll/pull/69#discussion_r1651356780

Fix /cbv/reset controller method name

---

app/app/controllers/cbv/shares_controller.rb
app/app/views/cbv/shares/show.html.erb
app/config/locales/en.yml

This button was accidentally going to the wrong URL, broken in the
refactor of 8b1a5c9.
This commit fixes it and adds a success message as a placeholder until
we build the confirmation/success page.
Fixes FFS-973.

Fix /cbv/share "Email to Caseworker" button

---

app/app/services/pinwheel_service.rb

When searching, we attempt to restrict search results to only those with
"paystubs" listed as a "job" that Pinwheel can perform for us. If
Pinwheel doesn't support the "paystubs" job, we can't get the data we
need for the product to actually work.
Some employers were breaking when clicking the "Select" button: these
employers didn't support the Pinwheel "paystubs" job, and we weren't
filtering them out of the results correctly due to a bug.
The issue here is that we were encoding the API request parameters
incorrectly, as:
POST /v1/search?q=foo&required_jobs[]=paystubs
The correct way to encode the `required_jobs` URL param, per API docs,
is:
POST /v1/search?q=foo&required_jobs=paystubs
(any additional values in the required_jobs array would be passed as
repeated parameters)
I ran some …

Fix PinwheelService to hide unsupported employers from search

---

app/app/services/pinwheel_webhook_manager.rb
app/config/initializers/ngrok_development.rb

When the Rails server is reloading, the Pinwheel webhook will be the
same URL since Ngrok hasn't restarted. It's inefficient to recreate the
webhook every time.
This commit updates the PinwheelWebhookManager to look for an existing
webhook with the same URL and events and don't do anything if that
already exists.

Update PinwheelWebhookManager to not recreate the same webhook

---

app/app/services/pinwheel_webhook_manager.rb
app/config/initializers/ngrok_development.rb

Not sure how this happened (Docker?) but if there's no USER env var,
then it will delete all other existing webhook subscriptions, since they
will all match the hash.
This both seeks to prevent creating a new empty-named webhook as well as
matching the exact name at the end of the webhook URL.

Don't delete all webhooks when ENV["USER"] is empty

---

bin/run-command.sh

We keep getting failures in GH Actions after merging because the task to
run migrations doesn't start. Why? We don't know. I've added `--debug`
here in hopes we'll get some clue, and also extended the timeout we'll
wait for logs from 100 seconds to 600 seconds (5 minutes).

Wait longer for bin/run-command log group to appear

---

bin/run-command.sh

This reverts commit 211485b4451b12805255446aa6564e308b951fdd. No need
for it since the problem was that the IAM Role didn't have permission to
read an SSM secret.

Revert "Wait longer for bin/run-command log group to appear"

---

docs/app/runbooks/deploy-failures.md

We've discussed as a team the desire to have runbooks for common
situations alongside our code.
This commit adds a quick runbook for "Deploy Failures" with two helpful
sets of instructions to debug deploy failures.

Add runbook for "Deploy Failures"

---

app/app/controllers/cbv/base_controller.rb
app/app/controllers/cbv/shares_controller.rb
app/app/controllers/cbv/successes_controller.rb
app/app/views/cbv/successes/show.html.erb
app/config/locales/en.yml
app/config/routes.rb
app/spec/controllers/cbv/shares_controller_spec.rb

Resolves [FFS-880](FFS-880)
1. Builds the /cbv/success screen
2. Links to the success screen from the share screen
1. I was unsure of where the link to the agency should go. Welcome to suggestions
2. I don't think we have a confirmation number to display to the user.
3. The copy second bullet point is not complete but I used what was in [the Figma](https://www.figma.com/board/yQQNaeCEYI1A6hGPyJkEE3/CBV-FigJam?node-id=5-751&t=hTWi2huGKW6AH1FM-0)

FFS-880: Build succes page

---

app/app/views/cbv/employer_searches/show.html.erb
app/config/locales/en.yml

Resolves [FFS-986](https://jiraent.cms.gov/browse/FFS-986)
Updated copy on the `employer_search` screen
I did not add the missing results button. That seems to be more part of [FFS-984](https://jiraent.cms.gov/browse/FFS-984).

FFS-986: Update copy on search page

---

.github/workflows/erblint.yml
app/.erb-lint.yml
app/.rubocop.yml
app/Gemfile
app/Gemfile.lock
app/app/controllers/cbv/agreements_controller.rb
app/app/controllers/cbv/successes_controller.rb
app/app/helpers/uswds_form_builder.rb
app/app/views/applicant_mailer/caseworker_summary_email.html.erb
app/app/views/applicant_mailer/invitation_email.html.erb
app/app/views/application/_banner_lock_icon.html.erb
app/app/views/application/_demo_site_banner.html.erb
app/app/views/application/_header.html.erb
app/app/views/application/_usa_banner.html.erb
app/app/views/cbv/agreements/show.html.erb
app/app/views/cbv/employer_searches/_employer.html.erb
app/app/views/cbv/employer_searches/show.html.erb
app/app/views/cbv/entries/show.html.erb
app/app/views/cbv/shares/show.html.erb
app/app/views/cbv/successes/show.html.erb
app/app/views/cbv/summaries/show.html.erb
app/app/views/cbv_flow_invitations/new.html.erb
app/app/views/layouts/application.html.erb
app/app/views/layouts/mailer.html.erb
app/app/views/pages/home.html.erb

N/A - I realized we should do these when giving Joe some CR feedback.
- **Add erb-linter to lint ERB files**
- **Add rubocop config to enforce 2-space indents**
Erblint is the standard way to lint Erb views. I've disabled the SpaceInHtmlTag linter because it forbids putting the close angle bracket on the subsquent line, e.g.:
```
<div
attribute="value"
>
<p>...</p>
</div>
```
Personally, I find that more readable than if the `>` were on the same line as `attribute="value"`.
It should run as part of this PR.

Add ErbLint for view linting

---

bin/run-database-migrations.sh

When adding an environment variable to AWS SSM, the task executor will
need access to read the environment variable in order to start up a
container. This is normally handled later in the deploy, when the
`bin/deploy-release.sh` script runs `make infra-update-app-service`. But
by then, the migrations container will already have failed.
This commit updates the targets for the pre-migration `terraform` run to
also update the `aws_iam_role_policy.task_executor` resource so that it
will have the permissions it needs to start up the migrations.

Update task_executor IAM policy before running migrations

---

bin/run-database-migrations.sh

I didn't test this before, and sure enough, it doesn't work.
See: https://github.com/DSACMS/iv-cbv-payroll/actions/runs/9765708170/job/26957251457
This seems to be the proper syntax:

Fix bin/run-database-migrations.sh script syntax

---

app/app/controllers/cbv/payment_details_controller.rb
app/app/views/cbv/payment_details/show.html.erb
app/config/locales/en.yml
app/config/routes.rb
app/db/migrate/20240715203948_change_additional_information_to_jsonb_column_on_cbv_flows.rb
app/db/schema.rb
app/spec/controllers/cbv/payment_details_controller_spec.rb
app/spec/controllers/cbv/summaries_controller_spec.rb

This PR modifies the existing `additional_info` column of the `cbv_flows` table from string column to a JSONB column. The JSON object is a hash consisting of keys which reference applicant payment account_id to an end user supplied comment.
Resolves [FFS-1087](https://jiraent.cms.gov/browse/FFS-1087)
> - Added migration that sets the default column value to an empty object e.g. `{}`
> - Adds new functionality to the Payment Details Controllers
> - Adds a comment box on the payment details page
> - Adds a form to the `payment_details` page that posts to the itself and then redirects to the `add_job` url
> - Adds unit and integration tests
> - Navigating back to the payment details page preserves the comment
The continue button for the `payment_details` page now acts a form submission which …

Support for multiple applicant comments. One comment per income source.

---

.github/workflows/cd-app.yml
README.md
docs/infra/set-up-aws-account.md
infra/accounts/nava-ffs-prod.730335532059.s3.tfbackend
infra/app/app-config/main.tf
infra/app/app-config/prod.tf
infra/app/database/prod.s3.tfbackend
infra/app/service/prod.s3.tfbackend
infra/networks/prod.s3.tfbackend
infra/project-config/networks.tf

Resolves FFS-1048.
This commit is the result of:
1. Adding AWS access keys to my local ~/.aws/credentials file (under a
new section for "prod")
2. Running:
```
AWS_PROFILE=prod make infra-set-up-account ACCOUNT_NAME=nava-ffs-prod
AWS_PROFILE=prod make infra-configure-app-service APP_NAME=app ENVIRONMENT=prod
AWS_PROFILE=prod make infra-configure-app-build-repository APP_NAME=app
AWS_PROFILE=prod make infra-configure-app-database APP_NAME=app ENVIRONMENT=prod
```
and their corresponding `update` make targets that actually create the AWS
resources.
3. Reviewing and making minor updates to the deploy documentation
One note is that this changes the shared build repository to be hosted
in production. It appears the infra template is architected around a
single shared container image registry, …

Add terraform config for CBV production environment

---

infra/app/app-config/env-config/main.tf
infra/app/app-config/env-config/outputs.tf
infra/app/service/main.tf
infra/app/service/massachusetts.tf
infra/app/service/outputs.tf

Resolves FFS-1197.
* Add env_config for MA MOVEIt bucket name
* Create the bucket and an IAM user to access it in a new
`massachusetts.tf` file.
* Output the access key details so we can send it to them
Co-Authored-By: George Byers <georgebyers@navapbc.com>
N/A
Already deployed. We tested that the credentials are able to access the bucket (and nothing more).

Add MA MOVEIt bucket configuration

---

infra/app/service/main.tf
infra/modules/email/main.tf

Finishes FFS-1022.
* Create a configuration set that requires TLS
* Set the default configuration set for the AWS SES sending identity
Note: The `default_configuration_set` parameter is only allowed for
`aws_sesv2_email_identity` resources (not the previously-used
`aws_ses_domain_identity` resource), so this commit upgrades the
resource to that. (It forces recreation.)
* Grant the task executor role permission to send email with the new
configuration set
See ticket.
Tested by running in development environment and verifying that an email still
goes through. I'm not sure how to test the failure mode of a non-TLS email
server. I will run it in production after merging.

Require TLS when sending emails via AWS SES

---

infra/app/app-config/main.tf
infra/app/app-config/staging.tf

No ticket.
Production deploys are currently failing due to the task not being able
to [pull the built image from the registry][1]. Upon further inspection,
this is probably because there is a mismatch between the configuration
for the "shared" AWS environment (which points to the "nava-ffs" dev
account and will be used by GH Actions when [building and pushing the
image][2]) and the actual [configuration of the "shared" Terraform
backend][3] (which points to the production account).
This commit harmonizes these environments in a hope that it just works.
I can't test this, since it's Github Actions, so I'm going to rely on
merging and seeing how it goes after that.
I also removed "staging" config for now, since we don't intend to have a
staging environment right now. I've left it …

Fix production deploy by pushing built images to prod registry

---

.github/workflows/ci-docs.yml
CONTRIBUTING.md
README.md
SECURITY.md
app/app/helpers/uswds_form_builder.rb
docs/app/runbooks/deploy-failures.md
docs/infra/https-support.md
docs/infra/module-architecture.md
infra/README.md

No ticket that I am aware of.
* Re-enable ci-docs job
* Here is it working: https://github.com/joeyg/iv-cbv-payroll/actions/runs/10173505564/job/28137733681?pr=3
* Looks like this was disabled [here](https://github.com/DSACMS/iv-cbv-payroll/commit/722642696bd7fcdead980b558f2b889fd560d57b).
* The links to https://hhs.responsibledisclosure.com/ result in a 403 when the tool runs so I have disabled the check for those links since they do work.
Running on PR

Re-enable ci-docs action

---

bin/publish-release.sh
infra/app/app-config/main.tf
infra/app/app-config/outputs.tf
infra/app/service/main.tf
infra/modules/service/access-control.tf
infra/modules/service/main.tf
infra/modules/service/variables.tf

N/A
Deploys to our demo (dev) environment were broken because they were
trying to pull the built image from the wrong AWS account (dev instead
of prod). This is because the service module was using a
"data.aws_ecr_repository" module to load the repository by name, despite
the fact that the ECR repository was in another account.
The fix for this is to pass in the "image_repository_account_id" to the
service module. We determine the value when processing the app-config by
calling the bin/account-ids-by-name.sh script, and looking for the
account ID for the account that contains the "shared" environment.
This commit also updates the publish-release.sh script. Although this
script worked (as the Github Action properly ran it in the shared
environment), I thought it would be good to …

Fix demo deploys by pulling image from correct account_id

---

app/app/controllers/api/pinwheel_controller.rb
app/app/controllers/application_controller.rb
app/app/controllers/cbv/base_controller.rb
app/app/controllers/webhooks/pinwheel/events_controller.rb
app/app/services/pinwheel_service.rb
app/app/services/pinwheel_webhook_manager.rb
app/config/site-config.yml
app/lib/site_config.rb
app/spec/lib/site_config_spec.rb
app/spec/services/pinwheel_service_spec.rb

First part of FFS-1179
- **Create "sandbox" site for internal testing**
- **Move Pinwheel API token into site-config.yml**
- **Allow specifying the Pinwheel environment per site**
Context in commit messages.
Next steps in PRs after this is merged:
* Add environment variables for "development" Pinwheel credentials
* Update NYC and MA sites to use development Pinwheel credentials
Tested by going through the flow locally.

Allow custom Pinwheel config per-site

---

app/config/environments/production.rb

FFS-1212
Healthchecks are failing after 7befe96 because they now try to redirect
to HTTPS. Since we can't configure the health checker to pass the
"X-Forwarded-Proto" header, let's just exempt this one path from the SSL
check.
Fixes a configuration bug preventing the deploy of new code.
I tested in development that the regex works as intended to exempt /health from
the SSL requirement.

Fix healthchecks by not requiring SSL

---

app/.env
app/config/site-config.yml
app/spec/controllers/api/pinwheel_controller_spec.rb
app/spec/controllers/cbv/entries_controller_spec.rb
app/spec/controllers/cbv/payment_details_controller_spec.rb
app/spec/controllers/cbv/shares_controller_spec.rb
app/spec/controllers/cbv/successes_controller_spec.rb
app/spec/controllers/cbv/summaries_controller_spec.rb
app/spec/controllers/cbv_flow_invitations_controller_spec.rb
app/spec/models/cbv_flow_spec.rb
infra/app/app-config/env-config/environment-variables.tf

Resolves FFS-1179.
This will allow us to test with real data for NYC/MA. To continue
testing with sandbox data, the "sandbox" site is left using a Sandbox
API key.
Deployment steps:
1. Rename the PINWHEEL_API_TOKEN in demo/prod to
PINWHEEL_API_TOKEN_SANDBOX. Generate a new API key for the
"development" and "production" Pinwheel environments and store them
in the respective env vars.
2. Deploy this.
3. Verify that the webhooks still work or set them back up again if they
don't.
4. Done.
5. Document it.
N/A
We'll test once it's live.

Change Pinwheel environment to "development" for NYC/MA

---

app/config/routes.rb

NA
Currently any page route will return a page even if provided a file extension. This has the effect of allowing any random file string to return a page, which fails security tests and could allow someone to provide a link to a working page that has profanities or other embarrassing strings.
This fixes that by only accepting HTML for HTML pages.

Only return HTML pages if a request has an HTML extension

---

app/app/controllers/users/omniauth_callbacks_controller.rb
app/spec/controllers/users/omniauth_callbacks_controller_spec.rb

N/A - Prioritized for family-and-friends testing.
Although we don't know what data we will get from the NYC callback,
let's add the handler for it here.
We will also have to add the URL to the list of Redirect URIs for our
"StagingIDP" Azure AD app.
N/A
Unable to test this locally due to being temporarily locked out of my Microsoft account.

Enable NYC SSO callback

---

app/app/views/layouts/application.html.erb

N/A - Prioritized because it is a warning currently occurring in the JS console of the site.
This came over by default with the template repo. We don't need it since
we're not intending to use it for metrics.
N/A
N/A

Remove analytics.usa.gov tracking

---

app/app/views/cbv/agreements/show.html.erb

N/A - Bug
The Pinwheel employer search will not work when a CSP is in effect,
since Pinwheel uses inline `<style>` tags. The CSP is disabled in the
controller, however, when the employer search page is requested via
Hotwire/Turbo, the headers that disable CSP don't apply to the root html
document.
So, disabling turbo on the previous page form will do the trick -
forcing the browser to do a full load of the next page with the proper
CSP.
N/A
Tested locally. I was able to reproduce the issue quite a bit before, but not at all afterwards.

Fix employer search inadvertently using CSP

---

app/config/initializers/content_security_policy.rb

N/A
The `style-src` directive blocks both elements (`<style>` and `<link
rel="stylesheet">`) as well as attributes (`<div style="...">`). The
directive can be split into two, which is necessary for us in order for
our inline styles on the payment_details page (and elsewhere) to render
properly.

Fix CSP to allow inline styles

---

app/app/controllers/cbv/base_controller.rb
app/app/controllers/cbv/expired_invitations_controller.rb
app/app/controllers/cbv/successes_controller.rb
app/app/models/cbv_flow.rb
app/app/models/cbv_flow_invitation.rb
app/app/views/cbv/add_jobs/show.html.erb
app/app/views/cbv/expired_invitations/show.html.erb
app/config/locales/en.yml
app/config/routes.rb
app/spec/controllers/cbv/add_jobs_controller_spec.rb
app/spec/controllers/cbv/agreements_controller_spec.rb
app/spec/controllers/cbv/employer_searches_controller_spec.rb
app/spec/controllers/cbv/entries_controller_spec.rb
app/spec/controllers/cbv/shares_controller_spec.rb

Resolves FFS-1200.
- **Add `/cbv/expired_invitation` path for too-old tokens**
- **Redirect to /cbv/expired_invitations after CBV flow is complete**
See commit messages for context/descriptions.
Tested that the expired invitation page displays in the following situations:
1. Following an invitation link that has had its `created_at` backdated to 15 days ago
2. Following an invitation link for a CBV flow I've already completed
Tested that we redirect to the homepage with an error message in the following situations:
1. Clicking "Back" on the confirmation page
2. Going to a page within the CBV flow after CBV flow has been previously completed
3. Going to a page within the CBV flow with no session at all
Tested that the following still works:
1. The flow as usual
2. CBV sandbox quickstart …

Expire CBV invitations after 14 days or completion

---

app/Gemfile
app/Gemfile.lock
app/app/models/cbv_flow_invitation.rb
app/config/site-config.yml
app/lib/site_config.rb
app/spec/controllers/cbv/entries_controller_spec.rb
app/spec/models/cbv_flow_invitation_spec.rb

Resolves FFS-1200.
* Change the expiry logic to allow for usage until 11:59pm Eastern on
the 14th day after the invitation has been sent
* Allow configuring the number of days per site
* Write tests to hopefully verify this (using the `timecop` library to
stub out the current time)
N/A
Tested locally to ensure the expiration logic generally worked. I didn't test setting my time zone to Eastern but I think that part will work.

Update invitation expiry to be a configurable number of days

---

infra/app/app-config/main.tf
infra/app/app-config/prod.tf
infra/project-config/networks.tf

Resolves FFS-1219.
It's really this easy! I just had to run the `make` commands to update
the network and the service, after deleting the duplicate Route53 zone
that was automatically created after registering the domain.
(Also fixed a bug in accessing the `account-ids-by-name` script that was
preventing it from being run in the `make infra-update-network` target.)
https://snap-income-pilot.com

Update production domain to snap-income-pilot.com

---

app/app/views/cbv_flow_invitations/new.html.erb
app/config/locales/en.yml

N/A - Fixes issue in #150.
We should be using the built-in support for HTML in I18n strings via an
`_html` suffix of the I18n key, as all variables interpolated into the
string are automatically HTML-sanitized.
See https://guides.rubyonrails.org/i18n.html#using-safe-html-translations
N/A

Use `_html` suffix for I18n string on invitations page

---

app/config/site-config.yml

N/A
Per meeting on August 13 with DTA, 21 days is too long and 14 days feels
better. (It may still be too long, but at least it aligns with NYC's
timeline.)
N/A
N/A - We'll test with backdated invites during final bug bash.

Change MA invites to be only valid for 14 days

---

app/app/views/cbv_flow_invitations/_sandbox.erb

N/A
Change the "sandbox" invitation page to use `date_picker` rather than an
unstyled date field. This makes it match the other invitation pages.
N/A
N/A

Fix sandbox invite page to use date picker

---

app/app/controllers/cbv/base_controller.rb
app/app/controllers/cbv/summaries_controller.rb
app/spec/controllers/cbv/entries_controller_spec.rb
app/spec/controllers/cbv/summaries_controller_spec.rb

Resolves FFS-1302.
It was broken because it was mistakenly redirecting to the expired
tokens URL. This commit tweaks how we do session management like so:
1. If the user hits the "Back" button after reaching the "success" page
(or goes to any other /cbv/ url), they will be redirected back to the
success page, with the CbvFlow still in their session (so the page
can render). This will create consistency so people don't
accidentally get locked out of their session after it's complete. We
will rely on session expiration (coming in the future) so that
reopening the browser after a long time does not return the user to
the success page.
2. That makes the "expired" page only used when *starting* a new flow
from a token.
3. After those changes, we can just skip the completeness check when …

Fix downloading PDF after completing CBV flow

---

README.md
app/app/helpers/application_helper.rb
app/app/views/cbv/add_jobs/show.html.erb
app/app/views/cbv/employer_searches/_employer.html.erb
app/app/views/cbv/missing_results/show.html.erb
app/config/i18n-tasks.yml
app/config/locales/en.yml
app/config/site-config.yml
app/lib/site_config.rb

Prerequisite to FFS-1235.
We've needed this ever since the initial concept of site config: a way
to differentiate copy based on which site is being viewed. Rather than
adding all of these strings to the site-config.yml, let's create a
helper method that looks for the key dynamically based on the current
site.
This commit removes the site config for `agency_help_link`,
`learn_more_link_text` and `learn_more_link_url` by replacing them with
some site-specific translations.
Confirmed that the following pages render properly:
* Add jobs
* Employer search ("0 results" message)
* Missing results

Add `site_translation` helper for site-specific copy

---

app/app/models/cbv_flow_invitation.rb
app/db/migrate/20240814192234_change_requirements_for_cbv_flow_invitations_fields.rb
app/db/schema.rb
app/spec/controllers/cbv_flow_invitations/ma_spec.rb
app/spec/controllers/cbv_flow_invitations/nyc_spec.rb
app/spec/models/cbv_flow_invitation_spec.rb

Closes [FFS-1300](https://jiraent.cms.gov/browse/FFS-1300)
- Updated `snap_application_date` to be required for all agencies
- `client_id_number` is now optional for NYC
- `middle_name` is now optional for all agencies
I've tested things locally and created tests to assert that the requirements are met

Updated NYC/MA required and optional fields

---

app/app/controllers/application_controller.rb
app/app/controllers/cbv/base_controller.rb
app/app/helpers/application_helper.rb
app/app/mailers/applicant_mailer.rb
app/app/views/applicant_mailer/invitation_email.html.erb
app/config/locales/en.yml
app/spec/controllers/cbv/entries_controller_spec.rb
app/spec/factories/cbv_flow_invitation.rb
app/spec/mailers/applicant_mailer_spec.rb
app/spec/mailers/previews/applicant_mailer_preview.rb
app/spec/mailers/previews/base_mailer_preview.rb
app/spec/mailers/previews/caseworker_mailer_preview.rb
app/spec/models/cbv_flow_spec.rb

Resolves FFS-1033.
- **Add "nyc" and "ma" versions of cbv_flow_invitation factory**
- **Fix mailer previews so they work with FactoryBot**
- **Update MA invitation email to include DTA logo**
See commit messages for a bit of context on each change.
Will do acceptance testing via mailer preview screenshots.
<details>
<summary>
<h2>Acceptance testing screenshots</h2></summary>
MA Applicant Email
NYC Applicant Email (this is unchanged)
</details>

Update MA invitation email to include DTA logo

---

app/app/controllers/application_controller.rb
app/app/controllers/cbv/base_controller.rb
app/app/javascript/controllers/cbv/employer_search.js
app/config/initializers/session_store.rb
app/config/locales/en.yml
app/spec/controllers/cbv/entries_controller_spec.rb

Finishes FFS-1294.
This commit tweaks the session logic by:
1. Configuring Rails to set the `Expires` cookie header, so browsers
will automatically stop sending the cookie. In this case, the user
will be redirected to the homepage with a message telling them to go
back and click the link again.
2. If the user clicks the invitation link again, they will resume from
the /entry page if they haven't connected any Pinwheel accounts, or,
if they have, they will resume from the payment details page of the
most recently-connected account.
N/A
Tested locally by deleting my cookie and checking that:
* Deleting cookie returns me to homepage with "session expired" message
* Deleting cookie after linking 1 employer, and clicking the link again takes
me to the payment details page for the employer I …

Expire session cookies after 30 minutes of inactivity

---

app/config/environments/development.rb
app/config/environments/production.rb

N/A - Reported by the team.
This reverts commit 5b788c91a1a1fb8192d805d017cf117284f8dd64.
Reading the definition of "SameSite=Strict" a bit closer, it says
> If a request originates from a different domain or scheme (even with
> the same domain), no cookies with the SameSite=Strict attribute are
> sent.
This was breaking SSO because the session cookie wasn't being sent to
the OmniAuth callbacks controller, since the navigation request
originates from a different domain (Microsoft's SSO page).
We don't actually need Set-Cookie=Strict for security reasons, it's only
a nice-to-have.
Tested locally - it was reproducible in an incognito window, and I was able to verify that this fix works.

Revert "Use "Strict" Set-Cookie SameSite value"

---

.github/workflows/markdownlint-config.json

N/A
These are all authenticated pages, so there's no way we'll actually be
able to tell whether the page exists there from our Github Action. And,
we've been getting some flaky failures here lately, so let's just skip
those links.
N/A
N/A

Ignore CMS confluence links in Markdown linting

---

app/app/helpers/application_helper.rb
app/app/mailers/applicant_mailer.rb
app/app/views/applicant_mailer/invitation_email.html.erb
app/spec/controllers/caseworker/cbv_flow_invitations/ma_spec.rb
app/spec/helpers/application_helper_spec.rb
app/spec/mailers/applicant_mailer_spec.rb

N/A - Bug I noticed
This fixes two bugs in the `site_translation` helper:
1. I realized that the `site_translation` helper wasn't sanitizing HTML the
same way that Rails's `t` helper does. I copied the implementation here.
Since it's getting unwieldly, I wrote some unit tests.
2. It wasn't displaying the correct header on the invitations page, because
the `@current_site` variable wasn't being set by the controller. Since this is
very weird for a function to rely on the definition of an
instance variable, let's go back to it just calling the `current_site`
method and make it explicit in the documentation string that each
controller/mailer has to define a `current_site` method.
N/A
Unit tests included, and I'm going to run through the site end-to-end to verify that no translations are …

Fix 2 bugs in the `site_translation` helper

---

app/app/assets/stylesheets/cbv.scss
app/app/controllers/cbv/base_controller.rb
app/app/views/layouts/application.html.erb
app/app/views/pages/home.html.erb
app/config/locales/en.yml
app/spec/controllers/cbv/entries_controller_spec.rb

Resolves FFS-1373.
* This implements the "/welcome" styles on the homepage
* I've made a second attempt at moving the footer down so it's not so
big for short pages (like the homepage).
* Since the homepage no longer has the "Start flow manually" button,
I've removed the functionality allowing starting a flow without an
invitation.
* Adds a "message_html" option to slim alert in case you want to do some
bold text or something in one of those alerts
N/A
Screenshots below.

Implement welcome page designs on homepage

---

app/app/controllers/users/omniauth_callbacks_controller.rb
app/spec/controllers/users/omniauth_callbacks_controller_spec.rb

N/A - Needed for NYC to log in for dynamic security scan.
Devise will convert the `email` field to lowercase, as configured by
config.case_insensitive_keys. When searching for an account, we need to
use Devise's `find_for_authentication` method so it will apply the same
transformation.
N/A
Regression test included. I also tested logging into an existing account as
well as a new account to verify it works.

Fix SSO bug for email addresses with capital letters

---

infra/app/app-config/env-config/environment-variables.tf

N/A
I added this to demo and prod ParamaterStores. The value in dev is our
eng team's google group, and the value in prod is the actual value.
We will test during E2E testing with NYC.

Add NYC_HRA_EMAIL as environment variable

---

app/app/views/cbv/payment_details/show.html.erb

Resolves https://nava.slack.com/archives/C06FC5TPAR3/p1724254549569479
Fixes a bug whereas the header and title for the payment details page was not being properly interpolated.
Visually inspected the browser page and compared the updated title with the current title

fixed header/title error occurring on payment details page

---

app/app/controllers/caseworker/cbv_flow_invitations_controller.rb
app/app/controllers/cbv/agreements_controller.rb
app/app/controllers/cbv/base_controller.rb
app/app/controllers/cbv/summaries_controller.rb
app/app/controllers/users/omniauth_callbacks_controller.rb
app/app/services/cbv_invitation_service.rb
app/config/newrelic.yml
app/spec/controllers/caseworker/cbv_flow_invitations/auth_spec.rb
app/spec/controllers/caseworker/cbv_flow_invitations/nyc_spec.rb
app/spec/controllers/cbv/entries_controller_spec.rb
app/spec/controllers/cbv/summaries_controller_spec.rb
app/spec/controllers/users/omniauth_callbacks_controller_spec.rb
infra/app/app-config/env-config/environment-variables.tf

Resolves FFS-705.
- **Track NewRelic event for CaseworkerLogin**
- **Add `site_id` to all NewRelic events**
- **Add `user_id` to ApplicantInvitedToFlow NewRelic events**
- **Add more metadata when tracking PDF share event**
- **Track seconds between invitation sent, flow start, and completion**
When we initially implemented NewRelic, it was too early and we didn't have all
the constructs necessary to instrument these product metrics. Now, we do, so
I've added metadata to various parts in order to capture all the metrics in the
attached ticket.
Now that the NewRelic account is set up, the easiest way to validate this change
is to merge this, build the dashboards, and then accept the ticket based off of
the dashboards as data flows in.

Implement remaining product metrics

---

app/app/controllers/cbv/base_controller.rb
app/app/models/cbv_flow_invitation.rb
app/app/services/data_retention_service.rb
app/spec/controllers/cbv/entries_controller_spec.rb
app/spec/services/data_retention_service_spec.rb

Resolves FFS-1416.
This converts the invitation's `has_one :cbv_flow` into a `has_many`.
Every time the user clicks the tokenized link again, they will have a
new CbvFlow started. This will prevent any compromise of the tokenized
link during the time between a user linking their payroll account and
completing the flow from revealing their session's data.
This is a launch requirement from NYC.
I will acceptance test this with Eryn by walking through various scenarios of
linking Pinwheel accounts, letting the session expire, and then clicking the
link again to verify that the associated payroll data is gone.

Create new `CbvFlow` object every time an invite link is clicked

---

app/app/views/applicant_mailer/invitation_email.html.erb
app/config/locales/en.yml
app/spec/mailers/applicant_mailer_spec.rb

Resolves FFS-1415
Modifies the copy for the body of the invitation email.
N/A
Screenshots will be provided for acceptance testing.

Use NYC-specific copy in applicant invitation email

---

app/app/views/application/_footer.html.erb
app/app/views/cbv/successes/show.html.erb
app/config/environments/ci.rb
app/config/environments/production.rb
app/config/initializers/devise.rb
app/config/locales/en.yml

N/A - Security review
- **Add rel="nooopener noreferrer" to external links**
- **Set `config.hosts` in production**
- **Use PKCE for Single Sign On**
I'm not sure whether PKCE will break something else. Matt - can you test this locally with your NYC login?
Tested SSO locally. The `hosts` change will have to be tested in production.

Address "Medium" security issues on latest NYC scan

---

infra/app/app-config/dev.tf

N/A
This upgrades the demo containers to match production: three ECS
containers with 1 vCPU and 4 GB RAM.
This is temporary, to handle increased load from a lot of scanning
activity will be occurring in the coming days.
The previous (default) values were a single container with 0.25 vCPU and
512 MB RAM.
N/A
N/A

Upgrade demo env to be three larger containers

---

app/app/controllers/users/omniauth_callbacks_controller.rb

N/A - An attempt to debug OTI issues.
Rather than giving a big scary red error, let's redirect back to the
authentication page so the proper Omniauth error will be displayed to
the user.
N/A
I verified this worked by clearing my cookie while doing a Microsoft SSO.

Redirect to caseworker entry page when Omniauth fails

---

app/app/controllers/cbv/base_controller.rb
app/app/controllers/cbv/expired_invitations_controller.rb
app/app/views/cbv/expired_invitations/show.html.erb
app/config/locales/en.yml
app/spec/controllers/cbv/entries_controller_spec.rb

Resolves FFS-1437.
The designs weren't ready when I initially implemented link expiry.
Let's implement them now.
Since the `@cbv_flow` is not available, we pass the site_id as a param
to the expiration controller.
N/A
Tested locally that an expired link takes us to the right version of the page.

Implement /expired page

---

app/app/views/caseworker_mailer/summary_email.html.erb
app/spec/factories/cbv_flow.rb
app/spec/mailers/caseworker_mailer_spec.rb
app/spec/mailers/previews/caseworker_mailer_preview.rb

N/A - Bug report in slack
We used `transmitted_at` by accident, but that won't be set until the
email succeeds at sending. Let's use `consented_to_authorized_use_at`
instead, which represents the time we should initially consider the CBV
flow "complete" and that it is ready to transmit.
N/A
Screenshot of the mailer preview below.

Fix "submitted date" on caseworker email

---

app/config/initializers/filter_parameter_logging.rb

N/A - Came up as I was looking at logs.
Let's get Rails to remove these parameters from the logs, to minimize
the risk that logs will inadvertently contain PII.
N/A
Tested locally:

Filter more parameters from logs

---

app/app/views/cbv/employer_searches/_employer.html.erb
app/config/locales/en.yml
app/spec/controllers/cbv/employer_searches_controller_spec.rb

Resolves FFS-1479.
The message had been informing users to exit the flow (assuming they had
previously linked an employer). We want to tell them to continue through
to review their report.
N/A
Screenshots below.

Fix employer search "no results" message for non-first jobs

---

app/app/controllers/caseworker/cbv_flow_invitations_controller.rb
app/app/views/caseworker/cbv_flow_invitations/new.html.erb
app/config/routes.rb
app/spec/controllers/caseworker/cbv_flow_invitations_controller/auth_spec.rb
app/spec/controllers/caseworker/cbv_flow_invitations_controller/ma_spec.rb
app/spec/controllers/caseworker/cbv_flow_invitations_controller/nyc_spec.rb

Resolves FFS-1350.
This error has happened a couple times. I couldn't reproduce why, so I'm
assuming that NYC staff just forgot the "/new" at the end of the link
and typed it in manually. To handle this, let's make it be a 404 rather
than 500 error.
While testing, I also cleaned up the parameters used on these redirects -
we don't have an invite secret anymore.
N/A
Tested invitation sending locally - still works.

Fix /:site/invitations to be a 404 instead of 500

---

app/config/newrelic.yml

N/A
The errors that become 404's (ActionController::RoutingError) are not
useful for us to receive as alerts, so let's skip sending them to
NewRelic.
N/A
N/A

Don't send 404 errors to NewRelic

---

app/app/views/applicant_mailer/invitation_email.html.erb

Resolves FFS-1355
Adds nyc logo.
Image of updated email:
Overlay using [pixel perfect](https://chromewebstore.google.com/detail/perfectpixel-by-welldonec/dkaagdgjmgdmbnecmcefdhjekcoceebi?hl=en) (image is correct size)

Add NYC HRA logo to invite email

---

app/app/controllers/cbv/base_controller.rb

From bug bash
The agency url website was hard-coded to the NYC url.

Update link to agency website

---

app/config/environments/ci.rb
app/config/environments/production.rb

Resolves FFS-1549.
These logos weren't loading because there was no `asset_host` specified.
Let's re-use the `DOMAIN_NAME` env var for it.
N/A
Tested in development by copying this config into development.rb and
verifying it was used in the Rails mailer.

1549: Fix logos in MA/NYC emails

---

app/config/environments/production.rb

Resolves FFS-1577.
* Set `config.action_mailer.action_host` instead of `config.asset_host`.
The fix in `e5b33456` for logos in emails accidentally broke PDF rendering.
The issue was that, when precompiling assets during the Docker build,
the DOMAIN_NAME environment variable is not set, leading to incomplete
URLs being referenced by the stylesheets built by the asset pipeline,
for example:
background-image: url(https:/assets/@uswds/uswds/dist/img/file[...].svg)
Since the same asset build is used for both demo and production, we
can't have a domain name in there. So, let's unset the
`config.asset_host`, so that no domain name is included during
compilation, and instead set the fine-grained
`config.action_mailer.action_host`, which is only used in the mailers.
Tested locally. Will have to …

1577: Fix error that happens during PDF rendering

---

app/app/controllers/cbv/summaries_controller.rb
app/app/services/cbv_invitation_service.rb
app/spec/controllers/caseworker/cbv_flow_invitations_controller/nyc_spec.rb
app/spec/controllers/cbv/summaries_controller_spec.rb

N/A
* Track `invitation_id` as an attribute of the sent-to-caseworker event
* Track the caseworker's email address as an attribute of the invited event.
This will allow us to track the caseworker emails of who is sending
invitations and who is supposed to be receiving the completed CSVs. We
can send caseworker email to NewRelic as it is not client PII.
Unit tests included.

Add NewRelic tracking for caseworker emails

---

app/bin/will-deploy

N/A
This script does a few things:
1. Fetches the latest code
2. Determines which commits have landed on `main` but haven't yet been
deployed to production (according to the production /health
endpoint.)
3. Formats a list of those commits suitable for pasting into slack.
It will recognize any 4-digit number followed by a colon in the commit
message title, and auto-link the Jira ticket (e.g. "FFS-1234:" or
"1234:")
In Terminal:
In Slack:
Hopefully when we automate deploys a bit better, we can call this script in CI
or something, but until then, this may be helpful for standardizing the format
of these messages.
Tested locally.

Add `bin/will-deploy` script to help communicate about deploys

---

app/Dockerfile

Resolves FFS-1630.
We need to install `libgpgme11` in order for the GPGME rubygem to be
able to encrypt the files.
This commit also upgrades git (as it seems to be necessary for the build
container) and alphabetizes the list of dependencies so it's easier to
determine where to add a new one in the future.
Paired with George.
Will test locally and after merging in Demo.

1630: Fix MA MOVEit transmission by installing gpgme

---

bin/update-infra-template

Related to FFS-1422.
* Add `bin/update-infra-template` script
The template-infra repo contains a script to upgrade itself, but this
script didn't work for me because it applies patches as an
all-or-nothing operation, and of course we have made modifications to
our terraform that will cause the patch application to fail.
To make it easier on myself, I wrote a script that automatically looks
for new released versions of `template-infra` and steps through
upgrading them one version at a time. Each version is applied by
applying the individual commits, and the pool soul doing the upgrade
will have to resolve any conflicts commit-by-commit.
Using this script, I was able to upgrade 3 minor versions and 4 patch
versions in about 3 hours of work. I still did have to clean up the git
history after …

Add script to ease upgrading template-infra

---

app/Dockerfile

N/A - Discovered during E2E testing
In production (only), our docker containers are read-only, which prevents the
GPG key from being added to the local keyring.
We should probably redo this to happen during build-time, but until then, let's
tell GPG to create our keyring in the writable directory.
N/A
Tested locally with an incantation of `docker run --read-only` and bind
mounting.

Fix MA GPG encryption in production

---

app/app/services/data_retention_service.rb
app/spec/services/data_retention_service_spec.rb

N/A
I was re-reading this code this morning, and discovered that we would
inadvertently redact incomplete CbvFlowInvitation's regardless of
whether they had expired or not.
This fixes the logic error and beefs up the tests.
N/A
N/A

Fix logic bug in DataRetentionService

---

app/app/controllers/webhooks/pinwheel/events_controller.rb
app/spec/controllers/webhooks/pinwheel/events_controller_spec.rb
app/spec/support/fixtures/pinwheel/request_platform_response.json
app/spec/support/pinwheel_api_helper.rb

Resolves FFS-1725.
1. Add unit tests for Pinwheel::EventsController
2. Add NewRelic event for PinwheelAccountSyncFinished
This will give us better visibility into Pinwheel failures.
Unit tests included.

1725: Add NewRelic event for PinwheelAccountSyncFinished

---

app/app/services/session_invalidation_service.rb
app/spec/services/session_invalidation_service_spec.rb

N/A - Fixes system error in logs.
The "before_logout" hook can be called with a `nil` user if the user has
already logged out (or their session timed out, presumably). In this
case, we can't do anything to invalidate the session because Devise
won't tell us which user it was related to. That's fine - we don't need
to invalidate the session, as Devise will already consider the session
timed out.
This commit fixes the error that comes up with `user` is nil in this
case.
N/A
N/A

Fix `invalidated_session_ids` system error when logging out twice

---

.github/workflows/markdownlint-config.json

N/A
It looks like HHS.gov is blocking automated tools from accessing its
pages. Let's ignore it when validating link destinations.
N/A
N/A

Fix documentation test failure by excluding HHS.gov

---

README.md
app/config/locales/en.yml

Resolves [#FFS-1750](https://jiraent.cms.gov/browse/FFS-1750)
1. On the /nyc/invitations page, observe that the date field's header has been updated and looks like this:
2. Then enter a date that is more than 30 days ago and submit the form. The error text should be updated and look like this:
3. Proceed through the workflow until you can download the PDF as an applicant. Verify that the prompt for "Application or recertification date" has changed to "SNAP application or recertification interview date"
4. Append `?is_caseworker=true` to the URL you used to download the PDF in step 3 to download the caseworker version of the same PDF. Verify the same change in step 3 was made in this PDF.
Use the Changes section when going through the NYC workflow. Observe the changes were made. No other …

FFS-1750: Update SNAP strings

---

app/lib/tasks/weekly_reports.rake
infra/app/app-config/env-config/scheduled_jobs.tf

Resolves FFS-1391.
The `template-infra` v0.12.2 release contains built-in cron job support
\- just in time, too. Let's give it a shot with our data retention and
weekly report jobs.
These changes will be deployed automatically by the GH Action since
they are part of the app service.
Will test in demo and verify that the data retention job is operating
correctly.

1391: Automate data retention and weekly report jobs

---

app/app/models/concerns/redactable.rb
app/app/services/data_retention_service.rb
app/config/newrelic.yml
app/spec/services/data_retention_service_spec.rb

N/A - Bugfix.
While running data redaction, I noticed that it was redacting every record
every time. To avoid wasting time on this every time redaction is run, let's
skip redacting any records that have previously been redacted.
Also, I noticed the error wasn't reported to NewRelic. I've added rake task
monitoring in an attempt to fix that.
Unit tests included. Will test manually in demo.

Fix data redaction to only redact records once

---

app/app/controllers/concerns/cbv/payments_helper.rb
app/spec/controllers/concerns/cbv/payments_helper_spec.rb
app/spec/controllers/concerns/cbv/reports_helper_spec.rb
app/spec/support/fixtures/pinwheel/request_end_user_paystubs_with_multiple_hourly_rates_response.json
app/spec/support/fixtures/pinwheel/request_end_user_paystubs_with_no_hours_response.json
app/spec/support/fixtures/pinwheel/request_end_user_paystubs_with_overtime_response.json
app/spec/support/fixtures/pinwheel/request_end_user_paystubs_with_sick_time_response.json
app/spec/support/fixtures/pinwheel/request_end_user_paystubs_with_start_bonus_response.json

Resolves FFS-1773.
* Add `earnings` entries with category="overtime" into the hours calculation.
See the comment in https://jiraent.cms.gov/browse/FFS-1773 for a
longwinded explanation of why this seems like the best way to make the
"Number of hours worked" field align better with reality.
Unit tests included for a number of cases I copied from real data. Only the
"earnings" hash is copied from real data, and I anonomyzied it somewhat by
rounding the numbers.

1773: Include overtime hours in "Number of hours worked" PDF field

---

infra/app/service/main.tf
infra/modules/email/variables.tf
infra/modules/email/webhooks.tf

Resolves FFS-1857.
This commit updates our email terraform to forward email delivery events
to NewRelic via EventBridge. (We don't need an SNS topic, as a result.)
The Email events are in NewRelic as custom events named "AWSSESEvent",
broken down with attributes for the SES event type and the message ID,
so we can make a funnel.
Unfortunately, we won't be able to tie these to the CBV Flow or
invitation just yet, but perhaps we can add a custom email header.
If we want to tie these in with CBV Flow or invitations, we could
instead send these to our application as HTTP webhooks using
EventBridge (by duplicating the code here).
Tested by running terraform locally to deploy this to our demo environment.
Then I sent a few emails to myself, and it seems to work!

1857: Add email open/deliver/bounce events to NewRelic

---

README.md
app/Gemfile
app/Gemfile.lock
app/app/services/pinwheel_webhook_manager.rb
app/spec/e2e/cbv_flow_spec.rb
app/spec/rails_helper.rb
app/spec/spec_helper.rb
app/spec/support/context/with_ngrok_tunnel.rb
app/spec/support/e2e_test_helpers.rb

Resolves FFS-1752.
This is a spike of a couple hours' work to show what E2E tests with
Capybara could look like. This implements "Task 1" of the tech spec
discussed on 9/27.
This is ready to be merged, as it incorporates changes we discussed as
a team on 9/30 (namely - replacing the hardcoded strings with I18n)
If you want to run it locally, you'll have to:
1. Create an `.env.test.local` with `PINWHEEL_API_TOKEN_SANDBOX` set to the proper value
2. Make sure your dev server is stopped (since only one `ngrok` can run at a time)
I ran it a bunch locally. It seems to work pretty well.

1752: Implement E2E tests with Capybara

---

.github/workflows/deploy.yml

Resolves FFS-1473.
This is an attempt to create a tag after each deploy so we can get
Github to help us see when any commit was deployed.
N/A
I don't have a good way to test this, so we'll have to see how it works
on our next production deploy.

1473: Create a git tag after deploying

---

app/config/locales/en.yml
app/config/locales/es.yml

[FFS-1865
](https://jiraent.cms.gov/browse/FFS-1865)
Replaced the `default` entry with `nyc` for the success page

1865: [bugfix] NYC applicant success page shows incorrect agency name.

---

app/app/controllers/cbv/summaries_controller.rb

Addresses 1488
Sets back to the default. The previous size was too large. 
This _did_ fix a minor issue where defaults were apparently ignored in production.
It doesn't address any of the substance of 1488, unfortunately.

1488: Reset PDF margins back to 10

---

.github/workflows/cd-app.yml

We need to give the deploy workflow `write` permission so it can post a
tag after the deploy finishes. I had forgotten to do it in my last commit:
https://github.com/DSACMS/iv-cbv-payroll/pull/315

Fix permissions on Github Actions token

---

app/package-lock.json
app/package.json

Resolves FFS-1931.
esbuild 0.20.2 was built with a version of Go that contains security
vulnerabilities. Let's upgrade to 0.24.0, which mentions using a more
recent go, in hopes that it fixes this.
N/A
I tested by running `npm run build`, which calls eslint. It succeeded.

1931: Upgrade esbuild 0.20.2 -> 0.24.0

---

.github/workflows/deploy.yml

N/A
Oops - git tags cannot contain colons.
N/A
Tested this locally and pushed the tag to Github here:
https://github.com/DSACMS/iv-cbv-payroll/releases/tag/deploy/prod/2024-10-17-15-15-39

Fix deploy tagging to use dashes

---

README.md
docs/app/runbooks/running-built-images-locally.md
docs/infra/vulnerability-management.md

N/A
This adds documentation for a couple things I just needed to do:
1. Download and run the docker container locally
2. Investigate a `grype` failure that didn't explain what files were
triggering the alert.
N/A
N/A

Improve docs for running local Docker images

---

app/app/controllers/cbv/base_controller.rb
app/app/controllers/cbv/employer_searches_controller.rb
app/app/controllers/cbv/expired_invitations_controller.rb
app/app/controllers/cbv/missing_results_controller.rb
app/app/controllers/cbv/successes_controller.rb
app/app/controllers/cbv/summaries_controller.rb
app/app/mailers/application_mailer.rb
app/spec/controllers/cbv/employer_searches_controller_spec.rb

Resolves [FFS-1839](https://jiraent.cms.gov/browse/FFS-1839)
Several new events were added:
1. On the Search page, the ApplicantAccessedSearchPage event fires
1. On the Summary page, the ApplicantAccessedIncomeSummary event fires
1. On the Success page, the ApplicantAccessedSuccessPage fires
1. On the session_timeout page, the ApplicantTimedOut event fires
1. On the missing_results page, the ApplicantAccessedMissingResultsPage event fires
1. On the expired page, the ApplicantLinkExpired event fires
Several new attributes were added to existing events:
1. To the ApplicantSearchedForEmployer event we added the :query attribute, which contains the query the user provided.
1. To the EmailSent event we added the :locale attribute, which contains the language the email was sent in (en or es). …

FFS-1839: Add more events to NewRelic tracking

---

app/Gemfile
app/Gemfile.lock

n/a
Resolves a critical a [vulnerability](https://nvd.nist.gov/vuln/detail/CVE-2024-49761)  in versions of rexml prior to `3.3.9` which prevents merging.

fixing vulnerability: https://nvd.nist.gov/vuln/detail/CVE-2024-49761

---

.github/workflows/check-ci-cd-auth.yml
.github/workflows/ci-infra-service.yml
.github/workflows/ci-infra.yml
infra/modules/service/main.tf

N/A - Bugfix
We had initially enabled this for security's sake, but it continues to
cause problems (first with GPG, now PDF rendering with
the auto-extracting wkhtmltopdf-binary gem).
Until we can have consistent behavior between demo and production
images, let's disable the readonly filesystem.
N/A
Will test in production.

Disable readonly filesystem in AWS ECS production

---

app/Dockerfile
docs/infra/vulnerability-management.md

N/A - Build issue on main branch.
* Upgrade curl
* Upgrade linux-libc-dev
* Upgrade and pin version of openssl
The upstream repos have a new version of these dependencies. Let's
upgrade to it. It would be really nice if these dependencies could be
managed automatically somehow.
N/A

Fix Docker build error by upgrading system dependencies

---

app/lib/tasks/invitation_reminders.rake

This is a quick fix to FFS-1836 that prevents reminder emails from being sent over and over to the same people. Previously, we used the update method, and it was failing because of validation issues on other fields. Now, we use the touch method, which will not have the same problem.

FFS-1836-2: quick fix to make reminder emails only send once each

---

app/Dockerfile
app/package-lock.json

N/A - Fixes broken build.
* Upgrade libpq 15.8 -> 15.9
* Upgrade npm cross-spawn 7.0.3 -> 7.0.6
The libpq 15.8 version is no longer in the package registry, causing Docker builds to fail.
The npm package cross-spawn has a security vulnerability.
Will rely on automated tests.

Fix build by upgrading two dependencies (libpq, cross-spawn)

---

app/app/components/pinwheel_data_point_component.rb
app/app/controllers/concerns/cbv/payments_helper.rb
app/app/helpers/view_helper.rb
app/app/views/cbv/payment_details/show.html.erb
app/app/views/cbv/summaries/show.pdf.erb
app/config/locales/en.yml
app/config/locales/es.yml
app/spec/controllers/concerns/cbv/payments_helper_spec.rb
app/spec/controllers/concerns/cbv/reports_helper_spec.rb
app/spec/helpers/view_helper_spec.rb
app/spec/support/test_helpers.rb

Resolves FFS-1934.
Ready for merge - 11/18.
N/A
Tested locally.

1934: Add hours breakdown to the payment details page

---

app/app/assets/stylesheets/cbv.scss
app/app/views/applicant_mailer/invitation_reminder_email.html.erb
app/spec/mailers/previews/applicant_mailer_preview.rb

1. Previously, the "Share your feedback" button's border wasn't visible when rendered in gmail. Now, it will be.
2. Previously, the headers in the reminders were all h3, which is not proper structure. Now, they're all h1, and there is no visible change.
1. In dev, if you're able, you can set up AWS in your console then make sure config.action_mailer.delivery_method is set to :sesv2 in your config/environments/development.rb. This should cause any triggered reminders to actually send to the listed email, which should allow you to observe the changes. This did not work for me, and so I plan to test more thoroughly in demo. However, the html was output to the console, and I was able to verify that the changes to the html/css appeared as I expected.
2. Similar to 1, observe that the h3 …

FFS-2086: Invitation reminder mailer fixes

---

app/config/locales/es.yml
app/spec/mailers/previews/applicant_mailer_preview.rb

Two Spanish strings were not translated in the NYC reminder email:
Now, it will look like this. Note that, after discussion, we decided NOT to translate the header string, since it's used in multiple places (not just these emails), matches the URL, and is too long in Spanish.
Take a look at es.yml and convince yourself that all Spanish translations are now present.
Once this is merged and in demo, trigger a reminder email by sending a new invite to your own email in Spanish, then call the following:
last = CbvFlowInvitation.last
last.created_at = 4.days.ago
last.snap_application_date = 1.hour.ago
last.save!
ApplicantMailer.with(cbv_flow_invitation: last).invitation_reminder_email.deliver_now
Verify the email you receive is completely in Spanish.

No ticket: added two missing Spanish translations for reminder emails

---

.github/pull_request_template.md
.github/workflows/markdownlint-config.json

N/A - No ticket
* Changes PR template to emphasize Acceptance Testing plan
This change is meant as a proposal to encourage a bit more team emphasis
on Acceptance Testing plan when creating new PRs. By selecting one of
the three main acceptance testing methods, the code reviewers will share
an understanding with the PR's author about future steps necessary
before the code is deployed to production.
* This …

Rewrite PR template to emphasize Acceptance Testing plan

---

app/spec/mailers/applicant_mailer_spec.rb

N/A
* Fix test for invitation reminder language
The previous test was never setting the language of the invitation to Spanish, so of course it was going to send in English.
It, itself, is a test.

Fix test for invitation reminder language

---

app/Gemfile
app/Gemfile.lock
infra/app/app-config/env-config/environment-variables.tf

Relates to [FFS-2175](https://jiraent.cms.gov/browse/FFS-2175).
This PR is for clean up efforts. We are keeping [MiniProfiler](https://github.com/MiniProfiler/rack-mini-profiler). I didn't see any specific instructions about placing mini profiler at the bottom of the Gemfile. It seems that requiring it below the database related Gems i.e. `gem "pg", "~> 1.1"` is the only requirement for accurate profiling. I verified this by leaving the Gemfile declaration where it currently is and at the end of the Gemfile and noticed no difference in the flamegraphs.
- Removal of `SKYLIGHT_AUTHENTICATION`  environment variable from ECS/Fargate via Terraform
- Removal of Skylight from Gemfile
Originally, we installed [Skylight](https://www.skylight.io/) in order to determine if we could gain additional …

FFS-2175: Removing Skylight from the project

---

app/app/controllers/api/pinwheel_controller.rb
app/app/javascript/controllers/cbv/employer_search.js
app/app/javascript/utilities/pinwheel.js
app/app/views/cbv/employer_searches/_employer.html.erb
app/app/views/cbv/employer_searches/show.html.erb
app/spec/controllers/api/pinwheel_controller_spec.rb

Resolves [FFS-2247](https://jiraent.cms.gov/browse/FFS-2247).
**Refactor "user action" tracking on employer search page**
> * Make the /api/pinwheel/user_action endpoint generic so it can receive
>   an "eventName" and arbitrary "attributes" for an event. This will be
>   used in subsequent commits for Pinwheel modal events.
> * Create new event, `ApplicantSelectedEmployerOrPlatformItem`, to
>   replace events `ApplicantSelectedPopularPayrollPlatform` and
>   `ApplicantSelectedPopularAppEmployer`. A unified event prevents the
>   javascript from having to know which event to send, and will also make
>   funnel analysis and future maintenance easier.
> * Add an attribute `is_default_option` to the new event so we can tell
>   apart clicks on the 12 default items from clicks on search …

FFS-2247: Track user modal interaction events from Pinwheel

---

app/Gemfile
app/Gemfile.lock
app/app/controllers/caseworker/cbv_flow_invitations_controller.rb
app/app/controllers/health_check_controller.rb
app/app/helpers/application_helper.rb
app/app/views/caseworker/cbv_flow_invitations/new.html.erb
app/docker-compose.yml
infra/app/app-config/env-config/environment-variables.tf

Resolves [FFS-1809](https://jiraent.cms.gov/browse/FFS-1809).
When a user is presented with the invitation page, if the user clicks on the send button multiple times, then multiple duplicate invitations will be generated and sent to the invitee. The purpose of this fix is to make sure that only one invite is generated.
Note: This work went through several iterations of approaches. This final approach is deemed most ideal as it maintains the use of the Turbo framework and allows for component reuse. 
1. app/app/views/caseworker/cbv_flow_invitations/new.html.erb - Wrap the invitation form in a turbo form so that form field errors will be rendered. 
2. app/app/helpers/application_helper.rb - Create a custom "form_with" that will assist with the proper rendering of page errors in the header …

FFS-1809: Disable multiple clicking on send invitation button

---

app/app/controllers/application_controller.rb
app/app/controllers/cbv/employer_searches_controller.rb

Resolves [FFS-1740](https://jiraent.cms.gov/browse/FFS-1740).
**FFS-1740: Fix unpermitted parameter developer warnings**
> These warnings were not causing any trouble, but they were creating
> confusion. Since I'm about to rework the analytics code, may as well fix
> this along the way.
> This fixes the warnings by not using "permit", since permitting specific
> attributes is mainly useful for mass assignment. In these controllers,
> by contrast, we directly index the params according to the indexes we're
> expecting, so no sense in also having the same list of allowed
> parameters being passed into `permit`.
* This change can be verified visually via screenshots attached below or by sending a link to a …

FFS-1740: [Tech Debt] Fix “unpermitted parameter” warning

---

app/app/controllers/caseworker/cbv_flow_invitations_controller.rb
app/app/services/cbv_invitation_service.rb
app/spec/services/cbv_invitation_service_spec.rb

Resolves [FFS-2402](https://jiraent.cms.gov/browse/FFS-2402).
**FFS-2402: Add delivery_method parameter to invite method**
> In addition to this, I removed the exception catching from the service
> itself, since the controller that calls the service also catches
> exceptions.
* Make sure to …

FFS-2402: Add delivery_method parameter to invite method

---

app/Dockerfile
app/Gemfile
app/Gemfile.lock
app/package-lock.json
app/package.json

Resolves [FFS-XXXX](https://jiraent.cms.gov/browse/FFS-XXXX).
* Make sure to notify the team once this PR is merged so we don't inadvertently deploy the unaccepted change to production. (e.g. `:alert: Deploy block! @ffs-eng I just merged PR [#123] and will be doing acceptance testing in demo …

Patching vulnerabilities | esbuild, net-imap

---

app/app/controllers/cbv/summaries_controller.rb

ApplicantSharedIncomeSummary and ApplicantAccessedIncomeSummary events now contain a correct value for account_count.
0. Go through the normal CBV workflow until you've shared the income summary with a caseworker.
1. Access Mixpanel and observe the two modified events. The account_count property should be set and seem reasonable.
2. Optionally, verify the same on NewRelic (but there's no reason to think it would differ).
* Acceptance testing should be done by **design** for visual changes, **product** for behavior/logic changes, **or both** for changes that …

FFS-2351: Change calculation of account_count to be correct in filed events

---

app/Gemfile
app/Gemfile.lock
app/app/models/response_objects/employment.rb
app/app/models/response_objects/identity.rb
app/app/models/response_objects/income.rb
app/app/models/response_objects/paystub.rb
app/app/services/pinwheel_service.rb
app/spec/helpers/cbv/pinwheel_data_helper_spec.rb
app/spec/services/pinwheel_service_spec.rb
app/spec/support/test_helpers.rb

Follow up from https://github.com/DSACMS/iv-cbv-payroll/pull/442 to migrate existing "response object" definitions to /models, leveraging Struct over Active Resource.
We needed a way to model API responses so we have explicit definitions for those things.
Our first attempt was in PinwheelService, where we leveraged ActiveResource (gem) to model these responses. We found this got us most of the way there with dot-notation accessor style and some clarity around the concepts. But they didn't help document the expected domain used throughout CBV.
This change moves the Paystub object into a ResponseObject that leverages Struct to enforce required fields. We define a `from_pinwheel` method to help map Pinwheel's values into our domain modeling
That said, our "domain modeling" here so far is …

FFS-2336: Move paystub, identity, employment, income into a response object

---

app/lib/mixpanel_event_tracker.rb

Mixpanel user profiles will now have accurate locations associated with them.
0. Create a brand new invite
1. Proceed through the CBV flow enough to file an event 
2. Click on the Distinct ID in Mixpanel for your new event and observe the User Profile section. It should contain your correct location (or the location of your VPN). Previously, it was just wrong (the theory is that it was the location of the AWS server being used).
* Acceptance testing should be done by **design** for visual changes, **product** for behavior/logic changes, **or both** for …

FFS-2397: Improve Mixpanel's user profile data

---

app/lib/generic_event_tracker.rb

In acceptance testing, we found that the user profile created did not ALWAYS match the location of the user creating the event. This is an experimental fix because I can't figure out how to test it locally... I need it to be running in demo so that request.ip and request.remote_ip resolve to something other than 127.0.0.1.
* This change is hard to test locally, so we'll test it in the demo environment …

FFS-2397-2: use remote_ip instead of ip

---

app/lib/generic_event_tracker.rb
app/lib/mixpanel_event_tracker.rb

Experimenting with fixing the user location Mixpanel issue by setting the $ip property rather than the ip property.
* Make sure to notify the team once this PR is merged so we don't inadvertently deploy the unaccepted change to production. (e.g. `:alert: Deploy block! @ffs-eng I just merged …

FFS-2397-3: experimental: use remote_ip instead of ip

---

app/app/assets/stylesheets/cbv.scss
app/app/controllers/application_controller.rb
app/app/controllers/help_controller.rb
app/app/javascript/controllers/help.js
app/app/views/help/_help_modal.html.erb
app/app/views/help/_help_topic_link.html.erb
app/app/views/help/index.html.erb
app/app/views/help/show.html.erb

Resolves [FFS-2453](https://jiraent.cms.gov/browse/FFS-2453).
- Swapped out the iframe with a turbo frame
- Removed the CSS for the now deprecated iframe
- Removed the JS functionality for refreshing the iframe URL …

FFS-2453: Replace Help Modal iframe with Turbo Frame

---

app/app/controllers/webhooks/pinwheel/events_controller.rb
app/app/models/payroll_account/pinwheel.rb
app/app/services/pinwheel_service.rb
app/spec/controllers/webhooks/pinwheel/events_controller_spec.rb
app/spec/support/fixtures/pinwheel/request_account_response.json
app/spec/support/pinwheel_api_helper.rb

Addresses [FFS-2466](https://jiraent.cms.gov/browse/FFS-2466).
This makes the model infer the pinwheel accounts supported jobs through the provided pinwheel_account_id.
We need to do this to make it easier to support multi-provider. The reason for this is that we want to create a payrol_acount earlier in the process, not when the webhook is received. In order to do that, we needed a tidier way to create payroll account objects. 
Before, we would look up the support jobs in the events controller and provide that to the model.
Now, we do that in an after_create hook. This means we can create payroll acounts anywhere without also needing to supply the supported jobs.
* This change can be verified visually …

FFS-2466: Infer supported jobs from within Pinwheel subclass

---

app/bin/will-deploy

Tim's been using prefixes like "FFS-1234-2:" to denote that it's his second PR addressing a certain ticket. Seems fine to me. Let's update the deploy script to linkify that syntax as well.
While here, it also makes the Github PR numbers, i.e. the "(#123)", a link to the PR on GH.
I added some tests to the script as well since those regular expressions are getting kind of bananas.
* This change is hard to …

Update bin/will-deploy script to handle "FFS-1234-2:" prefix

---

bin/run-command

N/A - Bugfix to address issue I've seen while deploying a few times now.
* Fix ThrottlingError when running migrations
I will upstream this after verifying it works in our repo. (I tested the AWS command locally and it seems to work well.)
We've been getting a ThrottlingError when running migrations a few times
(see [1], [2], [3]).
It's because the `--query` argument is evaluated client-side after
receiving the full list from the server, and therefore the
`describe-log-streams` call is paginating through all 174 pages of our
8300+ log streams just to select the single one we're looking for.
Github Actions' internet connection seems to be fast enough to hit the
[25 requests/second rate limit][4].
Let's use the `--log-stream-name-prefix` option instead to filter it
server-side. We can still …

Fix ThrottlingError when running migrations

---

app/Gemfile.lock
app/app/controllers/cbv/employer_searches_controller.rb
app/config/initializers/ngrok_development.rb

n/a
- Store Pinwheel initialization error during app config
- In dev only, display alert with initialization error during employer search
- Add `arm64-darwin-24` to Gemfile.lock platforms
We have a limit of 10 webhooks with Pinwheel before it will error out and cause issues during employer search. There is a line in the logs, but this PR makes it more obvious to developers that there's an issue from the UI. 
My computer adds `arm64-darwin-24` during `bundle install`.
* Acceptance testing should be done by **design** for visual changes, **product** for …

Display Pinwheel initialization error alert during employer search

---

.github/workflows/pr-reviewer-lottery.yml

N/A
* Fix reviewer-lottery by granting it access to manage PRs
I believe this may not work until it is merged to `main`. The issue is:
* Make sure to notify the team once this PR is merged so we don't inadvertently deploy the unaccepted change to production. (e.g. `:alert: Deploy block! …

Fix reviewer-lottery by granting it access to manage PRs

---

app/app/controllers/cbv/expired_invitations_controller.rb

Resolves [FFS-2585](https://jiraent.cms.gov/browse/FFS-2585).
This bug likely affects production, and the user would get the wrong error page.
When I attempt to access a CBV flow at an expired token, I see this crash page. http://localhost:3000/en/cbv/entry?token={token} 
The CBV Entry page was calling :set_cbv_flow (via BaseController's before_action methods) and redirecting to the expired_invitations_controller.  The problem is that expired_invitations_controller was then calling capture_page_view but it doesn't have a cbv_flow to log there and it crashes.
* Skip :capture_page_view in the expired_invitations_controller to prevent crash
* This change can be verified visually via screenshots attached …

FFS-2585 Fix Expired Invitations crash

---

.github/workflows/pr-reviewer-lottery.yml

N/A
* Define a "name" for the GH Action.
It was showing up as "test" in the GH actions list and was confusing. No longer! …

Give human-readable "name" to reviewer lottery GH Action

---

app/app/views/caseworker/cbv_flow_invitations/_ma.html.erb
app/app/views/caseworker/cbv_flow_invitations/_nyc.html.erb
app/app/views/caseworker/cbv_flow_invitations/_sandbox.html.erb

Resolves [FFS-2615](https://jiraent.cms.gov/browse/FFS-2615).
Validation on the First Name and Last Name fields is back!
Fixed form validation errors for name fields. Used the same pattern as the radio buttons with `<input>`. 
Considered adding a helper to our USWDS UswdsFormBuilder that could handle nested errors, but it got overly complicated and specific to solve this problem. This solution was more work in the view, but followed current conventions and was less of a 'surprise' to just keep the logic with our forms.
This regressed when we needed to display errors for nested fields, which broke the standard error display pattern. For nested error handling in our forms, we need to manually implement the error display.
* This change will not affect the user experience (bugfix, dependency …

FFS-2615: Form validation errors not applied to individual fields in CBV flow invitation form

---

app/app/controllers/api/argyle_controller.rb
app/app/javascript/adapters/ArgyleModalAdapter.ts
app/spec/controllers/api/argyle_controller_spec.rb
app/spec/javascript/adapters/ArgyleModalAdapter.spec.js
app/spec/javascript/fixtures/argyle.fixture.js

Resolves [FFS-2545](https://jiraent.cms.gov/browse/FFS-2545).
- Argyle controller sets the `isSandbox` flag based on the environment set in `client_agency_config.rb`
- `ArgyleModalAdapter` can receive and handle environment via token endpoint request
* Make sure to notify the team once this …

FFS-2546: Allow Argyle JS to support "production" environment

---

app/app/controllers/api/pinwheel_controller.rb
app/app/controllers/api/user_events_controller.rb
app/app/controllers/cbv/applicant_informations_controller.rb
app/app/controllers/cbv/base_controller.rb
app/app/controllers/cbv/employer_searches_controller.rb
app/app/controllers/cbv/entries_controller.rb
app/app/controllers/cbv/missing_results_controller.rb
app/app/controllers/cbv/payment_details_controller.rb
app/app/controllers/cbv/submits_controller.rb
app/app/controllers/cbv/successes_controller.rb
app/app/controllers/cbv/summaries_controller.rb
app/app/controllers/help_controller.rb
app/app/controllers/webhooks/pinwheel/events_controller.rb
app/lib/generic_event_tracker.rb
app/spec/controllers/help_controller_spec.rb

Corrected an issue Eryn noticed during acceptance testing: not all new events were properly getting the client_agency_id or locale attributes set. I fixed this for the new events and re-tested many of the existing ones.
There are a few events directly from pinwheel that still don't get these 100% correctly, but I think that's acceptable since so many other events do; it will be easy to determine what the values for these attributes likely were if they're missing, since they'll be on a user with many other events with these attributes set correctly.
* …

FFS-2540-4: corrected sending some attributes to the event logger

---

app/app/controllers/cbv/synchronizations_controller.rb
app/spec/controllers/cbv/synchronizations_controller_spec.rb

we only want to track the initial hitting of the page (which is done via the show action) when we're waiting for the webhooks to sync, rather than collect the poller as well.
Resolves [FFS-2739](https://jiraent.cms.gov/browse/FFS-2739).
Ensures tracking not applied when firing the update event, because that is polled for and therefore adds noise.
* You can test this by confirming that the PageView events only fire once when you hit the synchronizations page.

[FFS-2739] when the poller is firing to collect information, dont fire a pageview event

---

app/app/controllers/webhooks/argyle/events_controller.rb
app/app/controllers/webhooks/pinwheel/events_controller.rb
app/app/services/aggregators/format_methods/argyle.rb
app/app/services/aggregators/format_methods/pinwheel.rb
app/app/services/aggregators/response_objects/employment.rb
app/app/services/aggregators/sdk/argyle_service.rb
app/spec/controllers/webhooks/argyle/events_controller_spec.rb
app/spec/controllers/webhooks/pinwheel/events_controller_spec.rb
app/spec/services/aggregators/format_methods/argyle_spec.rb
app/spec/services/aggregators/format_methods/pinwheel_spec.rb

Resolves [FFS-2607](https://jiraent.cms.gov/browse/FFS-2607).
* **Add `employment_type` field to ResponseObjects::Employment**
This field, whose value is currently only `:w2` or `:gig`, is determined
by our own logic so we can use it in future stories (FFS-2542):
* For Pinwheel, we use a list of employer names from Pinwheel's support
team. We have to match the name because the /employments endpoint
doesn't have any ID to associate that employment with the employer
that was linked.
* For Argyle, we can just look at whether they classify the user as a
"contractor".
* This change can be verified visually via screenshots attached below or by sending a link to a local development environment to the acceptance …

FFS-2607: Add `employment_type` field to ResponseObjects::Employment

---

app/app/components/pinwheel_data_point_component.rb
app/app/helpers/view_helper.rb
app/app/views/cbv/submits/show.pdf.erb
app/config/i18n-tasks.yml
app/config/locales/en.yml
app/config/locales/es.yml
app/spec/helpers/view_helper_spec.rb

When using Argyle, the payment_details page will no longer crash in the Spanish locale.
Cleaned up our string tokens for the expectation of having multiple aggregators.
0. Switch to using Argyle (you must have argyle in your SUPPORTED_PROVIDERS list, as well as your ARGYLE_API_TOKEN_SANDBOX_ID and ARGYLE_API_TOKEN_SANDBOX_SECRET set in env.development.local)
1. Go through the cbv flow as normal
2. On the payment details page, switch to Spanish in the header
- At this point, the page should no longer crash
* Acceptance testing should be done by **design** …

FFS-2723: Updated strategy for aggregator string tokenization

---

app/app/helpers/view_helper.rb
app/spec/helpers/view_helper_spec.rb

N/A - Tiny bugfix needed for #560.
This was breaking by returning a hash when value was nil, because it
would look for a key like "aggregator_reports.employment_statuses.",
which I18n would happily resolve to:
```
{:employed=>"employed", :inactive=>"inactive", :terminated=>"terminated"}
```
This behavior seems incorrect, so we should ensure that a nil value in
results in a nil value out.
* This change is …

Fix translate_aggregator_value to handle `nil` value

---

app/app/services/aggregators/sdk/argyle_service.rb
app/app/services/provider_search_service.rb
app/spec/controllers/cbv/employer_searches_controller_spec.rb
app/spec/services/provider_search_service_spec.rb
app/spec/support/fixtures/argyle/bob/request_items.json
app/spec/support/fixtures/pinwheel/request_items_response.json
app/spec/support/pinwheel_api_helper.rb

Resolves [FFS-2753](https://jiraent.cms.gov/browse/FFS-2753).
**Update /employer_search precedence logic**
> Upon further discussion of requirements with Eryn, we want to update the
> precedence logic to be:
> 1. Search Argyle. If any result is an exact match (after basic string
>    normalization), then stop and show all Argyle results. If no exact
>    match, then
> 2. Search Pinwheel. If any result is an exact match (after basic string
>    normalization), then stop and show all Pinwheel results. If no exact
>    match, then
> 3. Show Argyle results, if any. If none, then
> 4. Show Pinwheel results.
> This commit implements that and refactors the tests a bit to be able to
> operate without stubbing the constant.
**Update Argyle search params to exclude unavailable results**
> [Argyle's …

FFS-2753: Update /employer_search precedence logic

---

app/app/models/cbv_applicant/sandbox.rb
app/lib/client_agency_config.rb
app/spec/models/cbv_applicant/az_des_spec.rb
app/spec/models/cbv_applicant/ma_spec.rb
app/spec/models/cbv_applicant/nyc_spec.rb
app/spec/models/cbv_applicant_spec.rb

i also like the spirit of the shared example test, but think a more direct call of the configuration drives which tests are required
Resolves ability to do sandbox invitations.
Fix sandbox invitation flow to be runnable again.
Restructures the tests so this will be less likely to happen in the future.
* Can attempt a sandbox invite.
* Make sure to notify the team once this PR is merged so we don't inadvertently deploy the unaccepted change to production. (e.g. `:alert: Deploy block! @ffs-eng I just merged PR [#123] and will be doing acceptance …

[FFS-2662] fix sandbox via introducing something for it to validate

---

app/app/services/aggregators/aggregator_reports/pinwheel_report.rb
app/app/services/aggregators/format_methods/pinwheel.rb
app/app/services/aggregators/response_objects/gig.rb
app/app/services/aggregators/sdk/pinwheel_service.rb
app/spec/controllers/cbv/summaries_controller_spec.rb
app/spec/controllers/webhooks/pinwheel/events_controller_spec.rb
app/spec/services/aggregators/aggregator_reports/pinwheel_report_spec.rb
app/spec/services/aggregators/format_methods/pinwheel_spec.rb
app/spec/services/aggregators/response_objects/gig_spec.rb
app/spec/services/aggregators/sdk/pinwheel_service_spec.rb
app/spec/support/fixtures/pinwheel/request_end_user_shifts_response.json
app/spec/support/pinwheel_api_helper.rb

Resolves [FFS-2550](https://jiraent.cms.gov/browse/FFS-2550).
- Fetch shifts data from Pinwheel
- Pinwheel integrated into the Gig `ResponseObject` struct
- Append gigs to Pinwheel report
- Test coverage for gigs, Pinwheel report and service with fixture
* Make sure to notify the team once …

FFS-2550: Calculate gig work hours using /shifts Pinwheel endpoint

---

app/app/controllers/api/argyle_controller.rb
app/app/javascript/adapters/ArgyleModalAdapter.ts
app/app/javascript/types/Argyle.d.ts
app/app/services/aggregators/sdk/argyle_service.rb
app/spec/controllers/cbv/payment_details_controller_spec.rb
app/spec/support/pinwheel_api_helper.rb

Resolves [FFS-2724](https://jiraent.cms.gov/browse/FFS-2724).
**FFS-2724: Use custom argyle flowId to allow multiple employers**
> Argyle was restricting users to only linking one account because any
> subsequent accounts would open an uncloseable "Your Connections" screen
> before allowing future subsequent account linking.
> This page can be disabled in Argyle settings by defining a custom
> "flow". We just have to pass this ID into the modal initialization.
> Tested locally and it worked like a charm.
* Acceptance testing should be done by **design** for …

FFS-2724: Use custom argyle flowId to allow multiple employers

---

app/app/views/cbv/summaries/show.html.erb

Resolves [FFS-2781](https://jiraent.cms.gov/browse/FFS-2781).
Before:
After:
This header was missing because we forgot an `=`.
* Make sure to notify the team once this PR is merged so we don't inadvertently deploy the unaccepted change to production. (e.g. `:alert: Deploy block! @ffs-eng I …

FFS-2781: Fix missing "Your Information" header on /summary

---

app/app/jobs/case_worker_transmitter_job.rb
app/spec/factories/cbv_flow.rb
app/spec/jobs/case_worker_transmitter_job_spec.rb

when pulling out the globals and moving into a worker, missed a global definition of argyle in the application controller.
added a test to help avoid this in the future.
* Generate argyle report locally.

 [FFS-2750] fix report generation worker refactor by adding additional argyle tests

---

app/app/controllers/api/user_events_controller.rb
app/app/helpers/view_helper.rb
app/app/javascript/controllers/index.js
app/app/javascript/controllers/language_controller.js
app/app/views/application/_header.html.erb
app/lib/generic_event_tracker.rb
app/spec/controllers/api/user_events_controller_spec.rb

Resolves [FFS-2779](https://jiraent.cms.gov/browse/FFS-2779).
**Adds:**
- Stimulus controller for language
- Mixpanel tracking when users switch languages in the header 
- Locale in all Mixpanel events, even without locale in url
- Events testing
**Testing:**
- Visit CBV entry
- Swap between Spanish and English
- Verify "UserManuallySwitchedLanguage" appears in log stream 
- Check all Mixpanel events have proper locale
* Acceptance testing should be done by **design** for visual changes, **product** for behavior/logic changes, **or both** for changes that …

FFS-2779: Event isn't logged when switching languages

---

app/.env
app/Gemfile
app/config/environment.rb
app/config/environments/development.rb
app/config/initializers/mission_control.rb
app/config/routes.rb
infra/app/app-config/env-config/environment-variables.tf

by default, the jobs dashboard engine we use leverages rails credentials. This trick lets us hook into the configuration directly instead so we can inject environment variables, since I don't think we have time right now to refactor into rails creds.
set MISSION_CONTROL_USER and MISSION_CONTROL_PASSWORD environment variables
run locally (bin/start_dev)
visit localhost:3000/jobs, putting in user/password you defined earlier.
if the page loads with a job dashboard, success!

 FFS-2750: add ability to see the dashboard across environments

---

app/app/controllers/webhooks/argyle/events_controller.rb
app/app/services/aggregators/sdk/argyle_service.rb
app/app/services/aggregators/webhooks/argyle.rb
app/app/services/argyle_webhooks_manager.rb
app/config/initializers/ngrok_development.rb
app/spec/controllers/webhooks/argyle/events_controller_spec.rb
app/spec/factories/webhook_request.rb
app/spec/models/payroll_account/argyle_spec.rb
app/spec/services/aggregators/sdk/argyle_service_spec.rb
app/spec/services/aggregators/webhooks/argyle_spec.rb
app/spec/services/argyle_webhooks_manager_spec.rb

Resolves [FFS-2784](https://jiraent.cms.gov/browse/FFS-2784).
**Allow passing in `config` when creating Argyle webhook subscriber**
> The config hash is useful for providing the `days_synced` argument to be
> able to register partially-synced events. This will be useful later for
> us for real. For now, this was just a testing thing that helped me out.
**Wait for Argyle `partially_synced` events (rather than `fully_synced`)**
> The Argyle sync anecdotally takes a very long time, and especially for
> gig accounts that have been open for a while (even if there isn't
> activity going back very far). We want to take advantage of Argyle's
> `paystubs.partially_synced` and `gigs.partially_synced` to allow the
> user to proceed to the /payment-details page even if the account may
> still …

FFS-2784: Update /synchronizations to only wait for a partial sync of 90 days

---

app/app/controllers/cbv/applicant_informations_controller.rb
app/app/models/cbv_applicant.rb
app/app/views/cbv/employer_searches/_employer.html.erb
app/config/locales/en.yml
app/config/locales/es.yml
app/spec/controllers/cbv/employer_searches_controller_spec.rb
app/spec/models/cbv_applicant_spec.rb

Changes
Links the next link on the missing results page such that it would proceed to the application information page, which they will need to fill out if in the LA flow. The application controller already checks if it is unnecessary to be there, so won't hurt non-LA flows while avoiding too much spreading logic.
Context for reviewers
In the future, there might be need for different action text. For now, a talk with design says they're ok with this language for now.
Testing instructions
* With an LA applicant, get one payroll account added, then search and fail to find a second payroll account. Click the button--> direct to the applicant information page.
* With an LA applicant, get one payroll account added, then search and fail to find a second …

FFS-2729: re-link continue button to applicant info page in case they want to continue forward

---

app/app/controllers/cbv/synchronizations_controller.rb
app/app/javascript/adapters/ArgyleModalAdapter.ts
app/spec/controllers/cbv/synchronizations_controller_spec.rb
app/spec/javascript/adapters/ArgyleModalAdapter.spec.js

Resolves [FFS-2675](https://jiraent.cms.gov/browse/FFS-2675).
- Fixed race condition in synchronization handling
- Simplify controller logic
- Set controller render partial with nil payroll accounts
- Testing
Users would get redirected to `/synchronization_failures` when `payroll_account` was `nil`, and we added a small timeout to alleviate it, but it wasn't enough and was brittle.
It was decided that we would handle redirecting to `/synchronization_failures` after a certain amount of polling or inability to retrieve data from webhook in a follow up ticket. 
Proceed through flow to synchronizations page as usual, observing that although the timeout is gone, synchronizations page is rendered not failures. …

FFS-2675: Remove artificial delay from ArgyleModalAdapter

---

app/app/controllers/cbv/synchronizations_controller.rb
app/app/models/cbv_flow.rb
app/app/models/payroll_account.rb
app/app/models/payroll_account/argyle.rb
app/app/models/payroll_account/pinwheel.rb
app/app/views/cbv/synchronizations/_indicators.html.erb
app/spec/controllers/webhooks/argyle/events_controller_spec.rb
app/spec/models/payroll_account/argyle_spec.rb
app/spec/models/payroll_account/pinwheel_spec.rb

First half of [FFS-2796](https://jiraent.cms.gov/browse/FFS-2796). This is the refactoring part of the branch, upon which the actual fix is implemented.
**Rename existing synchronization_status -> job_status**
> This is in preparation for adding a `synchronization_status` field
> to the PayrollAccount itself, which tracks the overall synchronization
> status (not just for a single job).
**Rename `#has_required_data?` -> `#necessary_jobs_succeeded?`**
> This name better reflects that the logic does not actually depend on the
> data that's present.
**Improve documentation of PayrollAccount base class**
**Rewrite #job_succeeded? to defer to #job_status(job)**
> Just some logic simplifications in these methods.
* This change will not affect the user experience (bugfix, dependency updates, …

FFS-2796-1: Rename sync tracking methods in PayrollAccount

---

app/app/models/payroll_account/argyle.rb
app/app/services/aggregators/webhooks/argyle.rb
app/spec/controllers/webhooks/argyle/events_controller_spec.rb
app/spec/factories/payroll_account.rb
app/spec/models/payroll_account/argyle_spec.rb

Resolves [FFS-2800](https://jiraent.cms.gov/browse/FFS-2800) and [FFS-2801](https://jiraent.cms.gov/browse/FFS-2801). Built atop #604.
**Reformat tests in Webhooks::Argyle::EventsController spec**
> * Rename the `describe` to make it more clear that the block is for
>   testing all webhooks in combination, not Argyle specifically (as all
>   the tests in this file are actually Argyle-specific).
> * Rename some of the other tests to be a bit more understandable what
>   the expectation is.
> * Remove one level of indenting.
**FFS-2800: Allow multiple webhook events to indicate success**
> We want to allow for either the `paystubs.partially_synced` or
> `paystubs.fully_synced` events to indicate the success of the "paystubs"
> job, since users with no paystubs will never get the …

FFS-2800: Allow multiple webhook events to indicate success

---

.pre-commit-config.yaml
Brewfile
infra/app/app-config/dev.tf
infra/app/app-config/env-config/outputs.tf
infra/app/app-config/env-config/variables.tf
infra/app/app-config/prod.tf
infra/app/service/deprecated_domains.tf
infra/app/service/main.tf
infra/modules/domain/certificates.tf
infra/modules/domain/variables.tf
infra/modules/service/dns.tf
infra/modules/service/variables.tf
infra/networks/deprecated_domains.tf
infra/project-config/networks.tf

Resolves [FFS-2798](https://jiraent.cms.gov/browse/FFS-2798).
To support this new domain, this commit adds terraform to:
1. Replace the old domain (snap-income-pilot.com) with the new domain.
2. We intend to use the new domain name with subdomains for
white-labeling. This commit adds an `additional_domains`
configuration variable that gets passed into the service module in
order to create the DNS records for the wildcard domain.
3. The wildcard domain will also need to be added to the TLS
certificate. This commit adds a new `subject_alternative_names`
configuration item to the `certificate_configs` variable that allows
for specifying additional hosts that should also be included in the
TLS certificate.
Finally, to remain backwards-compatible (at least temporarily) with …

FFS-2798: Add terraform to support ReportMyIncome.org

---

app/app/controllers/webhooks/argyle/events_controller.rb
app/app/models/payroll_account/argyle.rb
app/app/services/argyle_webhooks_manager.rb
app/spec/controllers/webhooks/argyle/events_controller_spec.rb
app/spec/factories/webhook_request.rb
app/spec/services/argyle_webhooks_manager_spec.rb

Resolves [FFS-2829](https://jiraent.cms.gov/browse/FFS-2829).
**FFS-2650: Track ApplicantReceivedArgyleData for partial data**
> We want to track events tracking sync time for 6 months of data, and
> when the data is fully synced (in addition to our existing
> ApplicantFinishedArgyleSync event, which also track sync time for 90
> days of data).
> This commit:
> * Adds a new webhook to subscribe to the partially_synced webhooks for 6
>   months of data (182 days)
> * Updates Webhooks::Argyle::EventsController to send Mixpanel events
>   when receiving these partially_synced events
> * Updates Webhooks::Argyle::EventsController to also send the
>   ApplicantReceivedArgyleData event when getting the
>   `users.fully_synced` event.
> There is one other change: updating our definition of when …

FFS-2829: Track multiple partially_synced durations during F&F testing

---

app/app/services/aggregators/format_methods/argyle.rb
app/app/services/aggregators/response_objects/identity.rb
app/spec/services/aggregators/response_objects/identity_spec.rb

* Argyle sends back the full SSN on the identities endpoint.  This ensures that we only capture the last 4 characters max.
- [x ] No acceptance testing needed
* Make sure to notify the team once this PR is merged so we don't inadvertently deploy the unaccepted change to production. (e.g. …

enforce last 4 of ssn for argyle

---

app/Dockerfile

remove libvips, because its an image processing library that had a security vuln and rather than update, why bump this unless we need it
This came up because of a recent trivy scan 
```
[info] checking github for release tag='v0.74.4' 
[info] fetching release script for tag='v0.74.4' 
[info] checking github for release tag='v0.74.4' 
[info] using release tag='v0.74.4' version='0.74.4' os='linux' arch='amd64' 
[info] installed /home/runner/work/_temp/16c6f042-66e4-4667-a5ee-3647b167ab34_grype/grype 
grype output...
NAME       INSTALLED         FIXED-IN          TYPE  VULNERABILITY   SEVERITY 
libvips42  8.[14](https://github.com/DSACMS/iv-cbv-payroll/actions/runs/14838901311/job/41656699205?pr=597#step:4:15).1-3+deb12u1  8.14.1-3+deb12u2  deb   CVE-2025-29769  High
```
* This change will …

remove libvips, because its an image processing library that had a security vuln and rather than update, why bump this unless we need it

---

app/Gemfile
app/Gemfile.lock
app/app/controllers/cbv/submits_controller.rb
app/lib/generic_event_tracker.rb
app/lib/new_relic_event_tracker.rb
app/spec/controllers/api/argyle_controller_spec.rb
app/spec/controllers/api/pinwheel_controller_spec.rb
app/spec/controllers/api/user_events_controller_spec.rb
app/spec/controllers/cbv/employer_searches_controller_spec.rb
app/spec/controllers/cbv/entries_controller_spec.rb
app/spec/controllers/cbv/payment_details_controller_spec.rb
app/spec/controllers/cbv/submits_controller_spec.rb
app/spec/controllers/cbv/summaries_controller_spec.rb
app/spec/controllers/help_controller_spec.rb
app/spec/controllers/users/omniauth_callbacks_controller_spec.rb
app/spec/controllers/webhooks/pinwheel/events_controller_spec.rb
app/spec/jobs/event_tracking_job_spec.rb
app/spec/lib/mixpanel_event_tracker_spec.rb
app/spec/lib/new_relic_event_tracker_spec.rb
app/spec/mailers/weekly_report_mailer_spec.rb
app/spec/rails_helper.rb

Resolves [FFS-2754](https://jiraent.cms.gov/browse/FFS-2754).
this removes the usage of the environment variable for job enqueueing, which enables us to remove maybe later.
this favors unit testing that event job tracking fires successfully as one set of tests, and the integration tests now don't check newrelic/mixpanel in favor of checking that the async job was fired.
To fix in a followup PR maybe: right now, if the job fails because it needed to connect to mixpanel or newrelic, the job will fail and retry the whole re-sync. at some point might be worth having a job fire off jobs? (mixpanel and newrelic seperately) [or rip out the newrelic events]
* go through the flow, make sure mixpanel events are still firing

 FFS-2754: finish extracting out maybe later

---

app/Dockerfile

not that its about libvips in particular, but this is doing the quick fix before taking time to address technical debt later.
why did this break things?
wkhtmltopdf depends on a host of dependencies, and I think libvips's dependencies is secretly saving us here. because wkhtmltopdf is a dragon of a dependency management problem, lets make that better another day.
error in particular:
Failed to execute:
["/usr/local/bundle/ruby/3.3.0/gems/wkhtmltopdf-binary-<IPV4>/bin/wkhtmltopdf", "--footer-right", "Income Verification Report | Page [page] of [topage]", "--footer-font-size", "10", "file:////rails/tmp/wicked_pdf20250506-68-5caeoy.html", "/rails/tmp/wicked_pdf_generated_file20250506-68-b0q2u5.pdf"]
Error: PDF could not be generated!
Command Error: pid <NUMBER> exit 127 …

bring back libvips because i suspect thats why the background worker started failing

---

infra/app/app-config/dev.tf
infra/app/app-config/env-config/outputs.tf
infra/app/app-config/env-config/variables.tf
infra/app/app-config/prod.tf
infra/app/service/main.tf
infra/app/service/newrelic.tf

Necessary so I can make the dashboards/alerts called for in [FFS-2817](https://jiraent.cms.gov/browse/FFS-2817).
**FFS-2817: Add NewRelic monitoring role to AWS terraform**
> We want to be able to ingest AWS metrics into NewRelic so we can set up
> dashboards, alerts, and the like. To do so, we need to give NewRelic
> readonly access to everything.
> We already had a limited form of NewRelic integration in our email
> module - I took this time to more properly support configuration of this
> parameter via variables in the env config.
* Acceptance testing …

FFS-2817: Add NewRelic monitoring role to AWS terraform

---

app/app/controllers/cbv/base_controller.rb

Resolves [FFS-2729](https://jiraent.cms.gov/browse/FFS-2729).
previous fix handled the case where NOT on the missing results page clicking through (search with 0 results --> click to proceed), but this handles the case where they directly click on missing results from searching and getting results back.
- [X ] Acceptance testing prior to merge
The previous fix corrected a link on the /missing_results page. But there is another link that can appear when you've already linked results and returned to the /employer_searches page. This PR fixes that link. To test:
Link an employer and return to the /employer_searches screen by clicking "yes I have more employers to link"
Search something that will produce some results, like "mcdonald"
Click the "Missing my employer" button, then press …

FFS-2729 guide someone who was going directly from a search page to missing results to get guided to applicant information

---

app/app/views/cbv/summaries/show.html.erb
app/config/i18n-tasks.yml
app/config/locales/en.yml
app/config/locales/es.yml

Various fixes found during AC testing of the original fix PR. These include:
1. /add_job: the link in the body text above the CTA opened a 404 page in LA. Not, it does not.
2. /summary: this string now reads "your Medicaid benefits" in LA.
2. Proceed through the flow to the pages mentioned above and make sure the copy you see reflects the fix described.
* Acceptance testing should be done by **design** for visual changes, **product** for behavior/logic …

FFS-2688: fixes round 2

---

app/app/services/aggregators/response_objects/income.rb
app/spec/services/aggregators/response_objects/income_spec.rb

In Argyle, pay_frequency should come from Identities.pay_cycle, not Identities.base_pay.period.
0. Set up your local dev instance to use Argyle (set SUPPORTED_PROVIDERS).
1. Navigate through the CBV workflow until you get to /payment details and observe the pay frequency. It should match what was returned in the Identities.pay_cycle value.
2. Also verify this value on on the PDF
3. Repeat the test using Pinwheel and verify that the pay frequency reporting is unchanged in these places
* Acceptance testing should be done by **design** for visual changes, …

FFS-2842: Update source of pay_frequency for argyle

---

app/app/helpers/report_view_helper.rb
app/config/locales/en.yml
app/config/locales/es.yml
app/spec/components/aggregate_data_point_component_spec.rb
app/spec/helpers/report_view_helper_spec.rb

Resolves [FFS-2852](https://jiraent.cms.gov/browse/FFS-2852).
* Fixes issue where all Spanish dates were off by a month (e.g. January 1 became 1 Febrero). 
* This is caused by Ruby's default Date string mappings set 0'th index to nil so that January has index position 1. 
* Copied all spanish date translation configuration from [i18n gem template](https://github.com/svenfuchs/rails-i18n/blob/master/rails/locale/es.yml). 
* Acceptance testing should be done by **design** for visual changes, **product** for behavior/logic changes, **or both** for changes that …

FFS-2852: Fix date format issues

---

.gitignore
infra/app/app-config/env-config/database.tf
infra/app/app-config/env-config/outputs.tf
infra/app/app-config/env-config/variables.tf
infra/app/app-config/prod.tf
infra/app/database/main.tf
infra/app/service/main.tf
infra/modules/database/main.tf
infra/modules/database/variables.tf
infra/modules/service/async_workers.tf
infra/modules/service/main.tf
infra/modules/service/variables.tf

Resolves [FFS-2870](https://jiraent.cms.gov/browse/FFS-2870).
- Add `results.sarif` from Checkov to our `.gitignore`
- Environment specific Aurora RDS min and max scaling to be set by Terraform config
- Performance insights to stop Checkov from complaining
- Preserve `enable_http_endpoint` functionality that was set via AWS console
- Environment specific SolidQueue worker num can be set via Terraform config
This hasn't been applied to dev or prod, but I did do a `terraform plan` to confirm the changes are what we expect.
* Acceptance testing should be done …

FFS-2870: Terraform configuration to support LA launch

---

app/app/controllers/webhooks/argyle/events_controller.rb
app/app/controllers/webhooks/pinwheel/events_controller.rb
app/spec/controllers/webhooks/argyle/events_controller_spec.rb
app/spec/controllers/webhooks/pinwheel/events_controller_spec.rb

Resolves [FFS-2828](https://jiraent.cms.gov/browse/FFS-2828).
- Added a new metric `paystubs_days_since_last_pay_date` which is the difference between the latest pay date of all of the applicant's paystubs and the date the report was generated.
* Make sure to notify the team once this PR is …

FFS-2828: Added paystubs_days_since_last_pay_date metric

---

app/app/controllers/webhooks/argyle/events_controller.rb
app/app/controllers/webhooks/pinwheel/events_controller.rb
app/spec/controllers/webhooks/argyle/events_controller_spec.rb
app/spec/controllers/webhooks/pinwheel/events_controller_spec.rb

* Added account_id onto Argyle and Pinwheel finished sync event logs as "identity_account_id".  This change is to allow faster investigations with provider data. 
View in Mixpanel on Sync event:
* Make sure to notify the team once this PR is merged so we don't inadvertently deploy the …

Add account_id to Mixpanel/New-Relic Finish Sync Events

---

app/app/controllers/webhooks/argyle/events_controller.rb
app/app/javascript/adapters/ArgyleModalAdapter.ts
app/app/jobs/application_job.rb
app/app/jobs/case_worker_transmitter_job.rb
app/spec/jobs/case_worker_transmitter_job_spec.rb

Resolves [FFS-2868](https://jiraent.cms.gov/browse/FFS-2868).
**Fix sending ApplicantSharedIncomeSummary when transmitting**
> The `event_logger` object was not defined (nor was `request`). The
> exception was being silenced. And, we removed the test of it during the
> refactor.
After the fix, here is an example of this event sending again:
**Fix ArgyleSuccess event to not set `user_id` attribute**
> This attribute is special, it is used by the MixpanelEventTracker to
> associate an event with a caseworker's session of that ID.
> Let's rename this to `argyle_user_id` so it doesn't collide there.
After the fix, here is an example of this event sending with the proper `distinct_id` (not caseworker-[uuid]):
**Remove duplicate event for ApplicantCreatedArgyleAccount**
> This event is being …

FFS-2868: Fix three metric bugs

---

app/app/services/aggregators/format_methods/argyle.rb
app/spec/services/aggregators/format_methods/argyle_spec.rb

Resolves Issue:
Employment Status was marked as “Furloughed”, even though she is unemployed.
* **Cause**: This is due to how we are normalizing the Argyle employment status ( active / inactive / terminated ) to Pinwheel’s definitions ( employed / furloughed / terminated). In particular, the issue here is that Argyle’s inactive is being translated to “furloughed”. According to Argyle, “inactive: typically indicates the employee left voluntarily, is on leave, or has not been active for a certain period of time.” This definition of inactive does not fully match the situation of being RIF’d, but “inactive” is still better than “furloughed”. 
* **Suggested resolution**: do not remap Argyle’s inactive as furloughed.
* Un-maps Argyle's inactive definition to pinwheel's "furloughed".  It will now …

Do not remap argyle's "inactive" unemployment status

---

app/app/controllers/webhooks/pinwheel/events_controller.rb
app/app/services/aggregators/aggregator_reports/aggregator_report.rb
app/spec/services/aggregators/aggregator_reports/argyle_report_spec.rb

Resolves [FFS-2828](https://jiraent.cms.gov/browse/FFS-2828).
Fixes a collision between changes in two branches.
We should probably do a followup PR where rspec runs in main branch CI, to catch potential issues like this in the future.
- [X ] No acceptance testing needed

FFS-2828: fix paystub event generation so if paystubs_days_since_last_pay_date includes an empty paystub date, still processes

---

.github/workflows/vulnerability-scans.yml
.grype.yml
.trivyignore

Currently, trivy and anchore are failing to build due to warnings on linux-libc-dev.  This adds ignore rules for the associated CVE's due to low risk of exposure and high risk of project impact for downtime this week. A separate PR will be opened to upgrade Ruby to 3.3.8 and remove these ignore rules.
* This change is hard to test locally, so we'll test it in the demo environment (deployed automatically …

temporarily ignore warnings for libc

---

app/app/mailers/weekly_report_mailer.rb
app/app/models/cbv_flow.rb
app/spec/mailers/weekly_report_mailer_spec.rb

Resolves [FFS-2690](https://jiraent.cms.gov/browse/FFS-2690).
Now that we have the generic links option which LA LDH uses, we should not generate weekly flows based on `CbvFlowInvitation` query, use `CbvFlow` instead and don't reference invitations at all for LA LDH
* Make sure to notify the …

FFS-2690: Send a report weekly to LA stakeholders

---

app/app/controllers/webhooks/argyle/events_controller.rb
app/spec/controllers/webhooks/argyle/events_controller_spec.rb

Resolves [FFS-2908](https://jiraent.cms.gov/browse/FFS-2908).
Added `client_agency_id` metric to `ApplicantFinishedArgyleSync` event.
* Make sure to notify the team once this PR is merged so we don't inadvertently deploy the unaccepted change to production. (e.g. `:alert: Deploy block! …

FFS-2908: Added client_agency_id to ApplicantFinishedArgyleSync

---

app/app/controllers/cbv/missing_results_controller.rb
app/app/views/cbv/missing_results/show.html.erb
app/spec/controllers/cbv/missing_results_controller_spec.rb

Resolves [FFS-2924](https://jiraent.cms.gov/browse/FFS-2924).
Replace the `@has_payroll_account` view variable with `@cbv_flow.has_account_with_required_data?` in the conditional for rendering the `/applicant_information` link. 
During our LA pilot an applicant encountered an [error](https://nava.slack.com/archives/C0792AR4570/p1747748131396709) which is a result of a bug in our view rendering logic whereas the `Continue to review my report` `(/applicant_information)` link was being rendered on the `/missing_results` page even if an applicant does not have a fully synced payroll account. 
The applicant clicked this button despite not having a `fully_synced` payroll account (or any payroll account linked for that matter) which resulted in the error above.
The view logic should first …

FFS-2924: Fix missing_results page view render logic

---

app/app/jobs/case_worker_transmitter_job.rb
app/spec/jobs/case_worker_transmitter_job_spec.rb

N/A - Other metric bug we noticed.
Rather than using `Time.now`, let's use
`consented_to_authorized_use_at`, since it represents when the user
finished the CBV flow. This will allow the calculated value of
`flow_started_seconds_ago` to not be changed if there is a long queue or
some error in processing the CaseWorkerTransmitterJob.
* This change is hard to test locally, so we'll test it in the demo …

Update `flow_started_seconds_ago` to be relative to consent page

---

app/app/services/provider_search_service.rb
app/spec/controllers/cbv/employer_searches_controller_spec.rb

Now, we filter a list of blocked employers from the search results from Argyle and Pinwheel.
See [this thread](https://cmsgov.slack.com/archives/C066XS5543S/p1747861309595409?thread_ts=1747856345.708169&cid=C066XS5543S). We decided to block certain employers who will always send us data in a format we don't expect (and which causes a crash). These employers were chosen because they represent unearned income, which is not what LA wants us to be reporting.
0. Set up to use argyle and pinwheel
1. Search for Social Security Administration, Veteran's Affairs, and Louisiana Workforce Commission (this never showed up anyway for some unknown reason, but we're blocking it at Patricia's request since it falls under a common unearned income category.
- Before, you would have seen matches that looked …

filter a list of employers from search results

---

app/app/models/cbv_applicant.rb
app/app/models/cbv_applicant/az_des.rb
app/app/models/cbv_applicant/la_ldh.rb
app/app/models/cbv_applicant/ma.rb
app/app/models/cbv_applicant/nyc.rb
app/app/models/cbv_applicant/sandbox.rb
app/spec/factories/cbv_applicant.rb
app/spec/models/cbv_applicant/az_des_spec.rb
app/spec/models/cbv_applicant/la_ldh_spec.rb
app/spec/models/cbv_applicant/ma_spec.rb
app/spec/models/cbv_applicant/nyc_spec.rb
app/spec/services/data_retention_service_spec.rb

Precursor to [FFS-2794](https://jiraent.cms.gov/browse/FFS-2794).
**FFS-2794: Update data redaction for LA LDH**
> We updated our data retention policy for Phase 2 pilots, but never
> updated the list of fields we redact. We no longer want to redact
> `case_number` since it is not sensitive PII.
* This change is hard to test locally, so we'll test it in the demo environment (deployed automatically after …

FFS-2794: Update data redaction fields for LA LDH

---

app/app/javascript/adapters/ArgyleModalAdapter.ts

N/A - Fix to improve investigation capability that would have helped me.
* **Track `accountId` and `userId` for Argyle modal events**
When we initially implemented these in FFS-2652, we were treating these
IDs as PII. After implementing that ticket, we redefined our definition
of PII to exclude non-sensitive identifiers such as these.
Since these will greatly help us investigate odd connection behavior in
the Argyle modal, let's stop sanitizing them.
* Acceptance testing should be done by **design** for visual changes, **product** for behavior/logic …

Track `accountId` and `userId` for Argyle modal events

---

app/app/components/report/monthly_summary_table_component.erb
app/spec/components/report/monthly_summary_table_component_spec.rb

Resolves [FFS-2980](https://jiraent.cms.gov/browse/FFS-2980).
- Gig hours rounded to the nearest tenth using `format_hours`
- Tests updated to check for rounding success
[Slack thread about tenths vs hundredths](https://cmsgov.slack.com/archives/C066XS5543S/p1749494135599339)
* Make sure to …

FFS-2980: Inconsistent hours format in gig summary table

---

app/app/components/report/monthly_summary_compact_component.erb
app/app/components/report/monthly_summary_compact_component.rb
app/app/components/report/monthly_summary_table_component.erb
app/app/components/report/monthly_summary_table_component.rb
app/app/components/table_cell_component.rb
app/lib/tasks/argyle_sandbox_data.rake
app/spec/components/report/monthly_summary_compact_component_spec.rb
app/spec/components/report/monthly_summary_table_component_spec.rb
app/spec/support/fixtures/argyle/empty/request_gigs.json
app/spec/support/fixtures/argyle/empty/request_paystubs.json
app/spec/support/fixtures/argyle/john_loanseeker_gig/request_accounts.json
app/spec/support/fixtures/argyle/john_loanseeker_gig/request_employment.json
app/spec/support/fixtures/argyle/john_loanseeker_gig/request_gigs.json
app/spec/support/fixtures/argyle/john_loanseeker_gig/request_identity.json
app/spec/support/fixtures/argyle/john_loanseeker_gig/request_paystubs.json
app/spec/support/fixtures/argyle/john_loanseeker_gig/request_user.json

Resolves [FFS-2985](https://jiraent.cms.gov/browse/FFS-2985).
* Adds helper text within monthly summary table if paystubs and gigs are missing.
* If no paystubs or gigs are found in a month, displays "N/A" within the data table.
* apply format_hours to monthly summary hours reporting
* Updates the argyle sandbox data rake task to pull gigs.
* Added john_loanseeker_gig and empty text fixtures for argyle.
* …

FFS-2985: Missing paystubs or gigs for Monthly Summary Table

---

app/app/controllers/cbv/submits_controller.rb

N/A - Request via Slack.
We only allow this in local development presently. Since AZ makes it
difficult to see the rendered caseworker report (as it is immediately
uploaded to SFTP, where we are unable to retrieve it), let's enable the
caseworker param in our demo mode as well.
* Make sure to …

Allow `is_caseworker` override param in demo environment

---

app/app/components/report/monthly_summary_table_component.erb
app/app/components/report/monthly_summary_table_component.rb
app/app/views/cbv/submits/show.pdf.erb
app/config/i18n-tasks.yml
app/config/locales/en.yml
app/config/locales/es.yml
app/spec/components/report/monthly_summary_table_component_spec.rb

Resolves [FFS-2983](https://jiraent.cms.gov/browse/FFS-2983).
**FFS-2983: Use "client" or "you" conditionally in monthly summary table**
> We want to render this component with different text when shown to an
> applicant ("you") versus caseworker ("client").
> I've introduced a new option for the report, `is_caseworker`, that will
> determine which variant of this component is being rendered.
Payment details page:
Client-facing income report:
Caseworker-facing report:
* Acceptance testing should be done by **design** for visual changes, **product** for …

FFS-2983: Use "client" or "you" conditionally in monthly summary table

---

infra/modules/database/backups.tf

Resolves [FFS-3047](https://jiraent.cms.gov/browse/FFS-3047).
- Updated the database backup plan to run daily at 12:30AM (UTC) with a 21 day retention period for snapshots.
```terraform
Terraform will perform the following actions:
~ resource "aws_backup_plan" "backup_plan" {
id       = "c17c8b4b-86f4-41c4-b2d1-ccb5a99176b5"
name     = "app-dev-db-backup-plan"
tags     = {}
- rule {
- completion_window        = 180 -> null
- enable_continuous_backup = false -> null
- recovery_point_tags      = {} -> null
- rule_name                = "app-dev-db-backup-rule" -> null
- schedule                 = "cron(0 7 ? * SUN *)" -> null
- start_window             = 60 -> null
- target_vault_name        = "app-dev-db-backup-vault" -> null
}
+ rule {
+ completion_window        = 180
+ …
```

FFS-3047: Update DB backups to run daily with a 21 day retention

---

app/app/models/cbv_applicant.rb
app/app/models/payroll_account.rb
app/app/services/aggregators/response_objects/identity.rb
app/spec/controllers/api/invitations_controller_spec.rb
app/spec/controllers/cbv/entries_controller_spec.rb
app/spec/factories/cbv_applicant.rb
app/spec/services/aggregators/response_objects/identity_spec.rb

Precursor to [FFS-3007](https://jiraent.cms.gov/browse/FFS-3007).
Two unrelated things necessary for FFS-3007. (I plan to rebase this on main since these are unrelated).
1. **Fix factories not instantiating CbvApplicant STI subclasses**
Due to the lack of `initialize_with` in the CbvApplicant factory,
FactoryBot always was instantiating a base CbvApplicant rather than the
desired subclass.
There was one spec failure, in the WeeklyReportMailer spec. Somewhere
deep within ActiveRecord, objects for this spec were getting created
with a `client_agency_id` being produced by the `.sti_name` method. This
method was not symmetric with `.sti_class_for`, as it should be, when
the name has a capital letter within it.
This also makes the same change to our other usage of STI, in
PayrollAccount, …

FFS-3007-1: Fix CbvApplicant instantiation and add first/last names to Identity object

---

app/app/services/agency_name_matching_service.rb
app/lib/tasks/az_des.rake
app/spec/services/agency_name_matching_service_spec.rb

Resolves [FFS-3007](https://jiraent.cms.gov/browse/FFS-3007).
- **Update agency name matcher to ignore capitalization**
- **Update agency name matching to be "exact" when only whitespace differs**
- **Add rake task to backfill agency name matches**
The last bit of this PR.
* Make sure to …

FFS-3007-3: Improve agency name match logic and add backfill script

---

.github/workflows/locale-sync.yml
.pre-commit-config.yaml
app/config/i18n-tasks.yml
app/config/locales/en.yml
app/config/locales/es.yml

There were a few problems:
1. The Check Locale Sync GitHub Action was breaking on main, but we don't want it to run on main. This ticket disables it on main, but it will still run on PRs.
2. The i18n-tasks health GitHub Action was breaking on main because there were several unused strings in our locale files, and there were several en strings that will never be translated to es (LA wind down copy). Now, the unused strings are deleted, and the LA wind down copy is listed as an exception in i18n-tasks.yml.
3. It was easy to commit problems like in 2 above because we never call the i18n-tasks unused check in our pre-commit hooks. Now, we do.
* This change can be verified visually via screenshots attached …

No ticket: fix i18n tasks failing inappropriately

---

app/app/assets/stylesheets/cbv.scss

Resolves [FFS-3038](https://jiraent.cms.gov/browse/FFS-3038).
Updates `z-index` of session timeout modal to a somewhat-absurd number so that it always shows in front of Argyle and Pinwheel modals.
- Because we're using `fixed` position on the session timeout modal all we need to do is this update
- I added a single 9 above the highest Argyle/Pinwheel `z-index`, but if there's a different preference for how to display higher let me know
* Acceptance testing should be done by **design** for visual changes, **product** for behavior/logic changes, **or both** …

Fix timeout modal being hidden behind Argyle

---

app/Gemfile
app/Gemfile.lock

Fixes vulnerability that's currently failing the build
- More granular update of `thor` than #843 if we want to get that in sooner without addressing as many changes
Wanted to open a quick fix to hopefully get this addressed with less review than automated PRs currently
* Make sure to notify …

No ticket: Update thor to address vulnerability

---

app/config/client-agency-config.yml
app/spec/controllers/pages_controller_spec.rb

Resolves [FFS-3135](https://jiraent.cms.gov/browse/FFS-3135).
- Pilot is enabled in dev/demo, but not production
* Make sure to notify the team once this PR is merged so we don't inadvertently deploy the unaccepted change to production. (e.g. `:alert: Deploy block! @ffs-eng I just merged PR …

FFS-3135: Re-enable LA pilot

---

app/app/controllers/cbv/base_controller.rb
app/app/controllers/cbv/entries_controller.rb
app/app/controllers/pages_controller.rb
app/config/client-agency-config.yml
app/config/routes.rb
app/lib/client_agency_config.rb
app/spec/controllers/cbv/base_controller_spec.rb
app/spec/controllers/cbv/entries_controller_spec.rb
app/spec/controllers/pages_controller_spec.rb

Resolves [FFS-3138](https://jiraent.cms.gov/browse/FFS-3138).
- Renames `source` query parameter to `origin` from the /start URL
- Add `origin` query parameter to `ApplicantClickedCBVInvitationLink` event metadata when present
- Only updates this specific event as well as events that were previously using `source`, but this could be expanded since this is being set on the session
- We had talked about how validation should work in the ticket, but I'm keeping it light for now to just standardizing casing and spaces. Happy to tighten that up, but if we have existing processes for deleting PII from Mixpanel I think the flexibility across deployments is a benefit
* This change can be verified visually via …

FFS-3138: Support tracking origin query parameter

---

app/config/locales/en.yml
app/config/locales/es.yml

[PR 853](https://github.com/DSACMS/iv-cbv-payroll/pull/853) introduced an error in the i18n-health ci pipeline due to unused string translations introduced by the PR.  This was not caught due to the pipeline not running the i18n-health check on that PR.  It was only run once it was merged to main.
* This change is hard to test locally, so we'll test it in the demo environment (deployed automatically after …

Fix i18n-health job by removing unused translations

---

app/app/views/cbv/payment_details/show.html.erb

Now, our rspec tests pass correctly and the /payment_details page renders appropriately again.
There was a straggler pinwheel_account reference due to different PRs merging automatically. #856 failed to get them all because I added another in the payment details show.erb. Now, that variable is renamed correctly. …

No ticket: rename straggling pinwheel_account variable

---

app/app/components/accordion_component.html.erb
app/app/components/table_header_component.html.erb
app/app/views/cbv/entries/show.html.erb
app/app/views/help/_help_topic_link.html.erb
app/app/views/help/index.html.erb

Three css issues are fixed: accordion spacing, table header height, and help modal topic button height all look normal now. …

FFS-3150: Various CSS fixes

---

app/app/controllers/cbv/generic_links_controller.rb
app/spec/controllers/cbv/generic_links_controller_spec.rb

Resolves [FFS-3140](https://jiraent.cms.gov/browse/FFS-3140).
- Implemented usage of CBV applicant id in generic link flow according to spec
- `ApplicantClickedGenericLink` tracking event with session info
- Testing
*Clear cookies*
- Visit generic link
http://localhost:3000/cbv/links/sandbox
- Check browser cookies -- should see:
`cbv_applicant_id: [encrypted value]`
- Visit same link again -- should reuse same applicant ID (different encrypted value)
- Check Mixpanel for "ApplicantClickedGenericLink" event
```
CbvApplicant.last # Check new or existing applicant, attributes reset
CbvApplicant.count # Should not increment with cookie in same browser
```
- Cookie appears after first visit
- Cookie persists across page refreshes  
- Same browser = same applicant ID
- Different browser = …

FFS-3140: Use CBV Applicant ID cookie for generic links

---

app/app/assets/stylesheets/cbv.scss
app/app/views/cbv/summaries/show.html.erb

1. The table header height on /summary is now the correct height (not in ticket -- ad-hoc fix)
2. Caseworker highlighting on the PDF now extends across the whole row again …

FFS-3194: Correct caseworker highlighting on PDFs

---

app/app/controllers/cbv/applicant_informations_controller.rb
app/app/controllers/webhooks/argyle/events_controller.rb
app/app/controllers/webhooks/pinwheel/events_controller.rb
app/spec/controllers/cbv/applicant_informations_controller_spec.rb
app/spec/controllers/webhooks/argyle/events_controller_spec.rb
app/spec/controllers/webhooks/pinwheel/events_controller_spec.rb

Resolves [FFS-3109](https://jiraent.cms.gov/browse/FFS-3109).
- Added `identity_age_range_applicant` when users submit applicant info form
- Removed `identity_age_range_applicant` from Argyle/Pinwheel "mega" events
- Age range now tracked when user enters DOB (not during payroll sync)
- Testing!
* This change is hard to test locally, so we'll test it in the demo environment (deployed automatically after …

FFS-3109: Client-entered age range property not set after client submits /applicant_info form

---

app/app/views/cbv/submits/show.html.erb

Resolves [FFS-3200](https://jiraent.cms.gov/browse/FFS-3200).
Add display-block class to allow for `white-space: normal` and handle any overflow case, including responsiveness
I chose to just adjust this one button, rather than anything global, since this is where the problematic string is and to focus on the bug/move quickly.
Wrapping text approved by design. Spanish translation for this string is significantly longer than English and our other strings.
* Acceptance testing should be done by **design** for visual changes, **product** for behavior/logic …

FFS-3200: Mobile scaling issue: submit button overflows when in Spanish

---

app/app/assets/stylesheets/cbv.scss
app/app/components/report/payments_deductions_monthly_summary_component.html.erb
app/app/views/cbv/submits/show.pdf.erb

Resolves [FFS-3206](https://jiraent.cms.gov/browse/FFS-3206).
- Add column width for /payment_details accordion table and PDF
The problem is more apparent in Spanish, since the strings are much longer!
* Make sure to notify the team once this PR is merged so we don't inadvertently deploy the …

FFS-3206: Misaligned columns in W-2 job accordions and report

---

app/Gemfile
app/Gemfile.lock

n/a
Manually adds the `mutex_m` gem which is required for Rubymine and debase to be able to debug the application. 
We [recently upgraded to Rails 7.2](https://github.com/DSACMS/iv-cbv-payroll/pull/878/files#diff-df49f2d9b819903541ac07251361bf63bbd5349ea3e5dcaf052403f0baed4965L83) which does not automatically include the `mutex_m` gem.
* This change is hard to test locally, so we'll test it in the demo …

Adding mutex_m gem since rails 7.2 removes it

---

app/app/controllers/cbv/base_controller.rb
app/spec/controllers/cbv/base_controller_spec.rb

Origin tracking used to keep the first received origin and persist it throughout the session, rejecting any subsequent origins. This was found to be unacceptable for go-live, and now we will update the origin any time we receive a different one.
I'm a little paranoid about this change because rejecting future origin differences seems to have been a purposeful decision made by Pat when he implemented [FFS-3138](https://github.com/DSACMS/iv-cbv-payroll/pull/850). Can anyone think of a reason this might have undesirable consequences? Maybe in other workflows? Pat is back tomorrow so I plan to ask for his input on this. I wonder why rejecting origin differences was so important.
0. Use the preview environment link below to construct a generic link by appending /en/cbv/links/sandbox to the end …

FFS-3220: Use most recent source for origin tracking

---

app/app/assets/stylesheets/cbv.scss

Footer used to be cut off at the bottom of the page. Now, it won't be.
* Make sure to notify the team once this PR is merged so we don't inadvertently deploy the unaccepted change to production. (e.g. `:alert: Deploy block! @ffs-eng I just merged PR [#123] and will be doing acceptance testing …

FFS-3229: make page footer not scrolled off the end of the page

---

app/app/controllers/pages_controller.rb
app/config/client-agency-config.yml
app/lib/client_agency_config.rb
app/spec/controllers/pages_controller_spec.rb

Resolves [FFS-3252](https://jiraent.cms.gov/browse/FFS-3252).
- Prevent session timeout redirect to generic links for AZ DES or any future pilot that has `generic_links_disabled`
- Tests
* Make sure to notify the team once this PR is merged so we don't inadvertently deploy the unaccepted …

FFS-3252: Investigate why some AZ flows are missing an invitation

---

app/config/client-agency-config.yml
app/lib/tasks/az_des.rake
app/spec/lib/az_des_rake_spec.rb

Resolves [FFS-3254](https://jiraent.cms.gov/browse/FFS-3254).
- Agency configuration toggle for CSV generation
- Rake task will abort for AZ
- Tests
There isn't really an earlier, centralized point to intercept these rake tasks and make something that is more generic while being agency configurable. This is a reusable pattern though. AZ is currently the only pilot sending CSVs.
* This change is hard to test …

FFS-3254: Make CSV file generation agency configurable and disable for AZ

---

app/app/controllers/cbv/applicant_informations_controller.rb
app/app/models/cbv_applicant.rb
app/app/views/cbv/summaries/show.html.erb
app/spec/controllers/cbv/applicant_informations_controller_spec.rb
app/spec/models/cbv_applicant_spec.rb

Resolves [FFS-3287](https://jiraent.cms.gov/browse/FFS-3287).
Move param concerns to controller, separate from display concerns
The summary page loop included a non symbol date of birth entry meant only for params validation. The translation looked up an invalid key and fell back to the string "Prompt," causing it to show up as a row label.
I think we should follow the convention of separating params and visual going forward, as a rule of thumb.
* Acceptance testing should be done by **design** for visual changes, **product** for behavior/logic changes, …

FFS-3287: Remove "Prompt" row from applicant info table on /summary

---

app/app/models/cbv_applicant/az_des.rb
app/app/models/concerns/redactable.rb
app/app/services/data_retention_service.rb
app/lib/tasks/az_des.rake
app/spec/models/cbv_applicant/az_des_spec.rb
app/spec/services/data_retention_service_spec.rb

Resolves [FFS-3375](https://jiraent.cms.gov/browse/FFS-3375).
Running `rake az_des:redact_case_numbers` will redact all the `case_number` for all applicants in the AZ Pilot.
- Accepted locally by running task and changing the task to run against `sandbox` but decided to make it an az specific task just to cut down on any potential for user error when run on higher environments. 
* This change is hard to test …

FFS-3375: Allow for redacting case_number in AZ

---

README.md
app/app/services/json_api_signature.rb
app/app/services/transmitters/json_transmitter.rb
app/db/seeds.rb
app/lib/json_api_receiver.rb
app/spec/services/json_api_signature_spec.rb
app/spec/services/transmitters/json_transmitter_spec.rb

Resolves [FFS-3380](https://jiraent.cms.gov/browse/FFS-3380).
- Added HMAC sha512 request signature to JSON transmitter
- API key lookup (oldest active for an agency)
- Updated Sinatra receiver to optionally verify signatures
- `JsonApiSignature` util
**Start the test receiver**
```bash
bin/api-test
```
**No signature**
```bash
curl -X POST http://localhost:4567/ \
-H "Content-Type: application/json" \
-d '{"test":"data"}'
```
**Invalid signature**
```bash
curl -X POST http://localhost:4567/ \
-H "Content-Type: application/json" \
-H "X-IVAAS-Timestamp: 1640995200" \
-H "X-IVAAS-Signature: super-invalid-signature" \
-d '{"test":"data"}'
```
**Valid signature**
```bash
ruby -r './app/services/json_api_signature' -e 'puts JsonApiSignature.generate("{\"test\":\"data\"}", "1640995200", …
```

FFS-3380: Add signature verification to JSON API

---

app/app/controllers/cbv/base_controller.rb
app/config/client-agency-config.yml
app/lib/client_agency_config.rb
app/spec/controllers/cbv/entries_controller_spec.rb

Resolves [FFS-3419](https://jiraent.cms.gov/browse/FFS-3419).
**Always allow invitation reuse**
> We had a setting, allow_invitation_reuse, which would enable a tokenized
> link to be reused. We recently forgot to set this value to true for LA,
> since we've updated our product thinking such that this behavior is the
> default.
> As such, let's simplify the logic here so that these links can always be
> reused.
I am not quite sure we want to do this from a product perspective. I will verify that as part of acceptance testing.
* Acceptance testing should be …

FFS-3419: Allow all Tokenized Links to be reused, including in LA

---

app/app/controllers/cbv/generic_links_controller.rb
app/spec/controllers/cbv/generic_links_controller_spec.rb

Resolves [FFS-3376](https://jiraent.cms.gov/browse/FFS-3376).
- Add safe navigator as requested + test that fails and duplicates error before passing
* Make sure to notify the team once this PR is merged so we don't inadvertently deploy the unaccepted change to production. (e.g. `:alert: …

FFS-3376: Add safe navigation operator to event logging code
