DSACMS/iv-cbv-payroll

- app/Gemfile
- app/Gemfile.lock
- app/config/environments/production.rb
- infra/app/service/main.tf
- infra/modules/email/main.tf
- infra/modules/email/variables.tf
This PR provisions AWS SES resources as done on a different project.
Authentication is done via the IAM Role and, we believe, passed into the app
container processes via environment variables by the ECS system.
[FFS-802](https://jiraent.cms.gov/browse/FFS-802)
> Set up AWS SES

- .github/workflows/build-and-publish.yml
Resolves [https://jiraent.cms.gov/browse/FFS-857](https://jiraent.cms.gov/browse/FFS-857)
- Uncommenting the continuous deployment code to trigger build and publish.
> uncommenting the push to main trigger for continuous deployment

- app/app/controllers/api/pinwheel_controller.rb
- app/app/controllers/cbv_flows_controller.rb
- app/app/controllers/webhooks/pinwheel/events_controller.rb
- app/app/services/pinwheel_service.rb
- app/db/migrate/20240613154132_add_pgcrypto_extension.rb
- app/db/migrate/20240613154226_add_end_user_id_column_to_cbv_flows.rb
- app/db/schema.rb
[Resolves ](https://jiraent.cms.gov/browse/FFS-883)
- Uses the CbvFlow to track end_user_id within the Pinwheel API context
- Supplies that end_user_id upon Link token creation
- Queries for accounts associated with that end_user_id
- Uses those accounts to query for associated paystubs
> Query for accounts/then payroll

- app/app/controllers/cbv_flows_controller.rb
- app/app/views/applicant_mailer/invitation_email.html.erb
- app/config/locales/en.yml
- app/spec/mailers/applicant_mailer_spec.rb
- **Improve styling on ApplicantMailer#invitation_email**
- **Fix rubocop**
> Improve styling on ApplicantMailer#invitation_email

- app/app/views/cbv/entries/show.html.erb
- app/config/locales/en.yml
Resolves [FFS-985](https://jiraent.cms.gov/browse/FFS-985)
Updated the copy on the `entry` screen.
This is my first PR for this repo so please let me know of any conventions that should be followed.
1. Checkout `jgasiorek-ffs985` branch
2. `docker compose up`
3. Navigate to `http://localhost:3000/cbv/entry`
> FFS-985: Update copy on entry page

- app/app/controllers/cbv/agreements_controller.rb
- app/app/controllers/cbv/base_controller.rb
- app/app/views/cbv/agreements/show.html.erb
- app/config/locales/en.yml
- app/config/routes.rb
Resolves FFS-983
1. New agreement page for /agreements url
2. Link to new agreement page from /entry page
1. Start at beginning of the flow
2. Navigate through to employer search page
> FFS-983: Agreement Page

- app/app/controllers/cbv/add_jobs_controller.rb
- app/app/controllers/cbv/base_controller.rb
- app/app/controllers/cbv/payment_details_controller.rb
- app/app/javascript/controllers/cbv/employer_search.js
- app/app/views/cbv/add_jobs/show.html.erb
- app/app/views/cbv/payment_details/show.html.erb
- app/config/locales/en.yml
- app/config/routes.rb
- app/spec/controllers/cbv/add_jobs_controller_spec.rb
- app/spec/controllers/cbv/payment_details_controller_spec.rb
Resolves [FFS-936](https://jiraent.cms.gov/browse/FFS-936)
The design ticket for this work, [FFS-908](https://jiraent.cms.gov/browse/FFS-908) was marked as complete. I assumed that meant that the engineering work could be done but I can close this PR if that was not a correct assumption.
1. Adds add_job screen
2. Adds payment_details screen
3. Changes flow to  employer_search -> payment_details -> add_job
NOTES:
1. This does not implement the second add_job screen that asks "Do you have an online payroll provider for this job?".
2. The UI for the payment details screen does not have much to it. I wasn't sure what to put for the paystub items.
> FFS-936: Multi-employer search

- .gitignore
- app/app/controllers/cbv/base_controller.rb
- app/app/views/cbv/payment_details/show.html.erb
- app/config/locales/en.yml
Resolves [FFS-1086](https://jiraent.cms.gov/browse/FFS-1086)
Updates the payment details page to list payments by pay dates utilizing USWDS design components. Multiple deductions are accounted for.
> Update Payment Details to use USWDS Design Components

- app/Dockerfile
- app/Gemfile
- app/Gemfile.lock
- app/app/controllers/concerns/cbv/payments_helper.rb
- app/app/views/cbv/agreements/show.html.erb
- app/app/views/cbv/payment_details/show.html.erb
- app/config/locales/en.yml
- app/docker-compose.yml
- app/spec/controllers/concerns/cbv/payments_helper_spec.rb
Resolves [FFS-1167](https://jiraent.cms.gov/browse/FFS-1167)
- Changed copy of payment details page
- Changed color of continue button
- Updated table to be stacked table
> Update UI for Payment Details Page

- app/config/environments/ci.rb
- app/config/environments/production.rb
Resolves FFS-1212.
Both demo and production actually are runinng in production, so we
should be able to test this in demo.
Security review remediation item.
Will test in demo.
> Require SSL/TLS for all web requests in production environments

- infra/app/app-config/env-config/environment-variables.tf
N/A
Adds environment variables that were configured in 2eb7e92.
The values for these variables have already been configured in the AWS accounts.
This will be deployed by the deploy task.
> Add SSO environment variables to infra config

- app/Gemfile
- app/Gemfile.lock
- app/app/controllers/cbv/employer_searches_controller.rb
- app/app/views/application/_usa_banner.html.erb
- app/config/initializers/content_security_policy.rb
N/A - Prioritized because I would love a clean OWASP scan before we have to review it on Friday.
- **Run `bundle update`**
- **Upgrade newrelic 8.16.0 -> 9.12.0**
- **Fix CSP configuration for app**
See commit messages.
Tested locally by going through SSO and Pinwheel flows successfully.
> Fix CSP configuration for app

- app/Dockerfile
N/A
Docker build only.
I'm getting build errors with 15.7.
Docker build works locally, after this fix.
> Upgrade libpq 15.7 -> 15.8

- app/app/controllers/users/omniauth_callbacks_controller.rb
N/A
This is best practice from a security/audit logging perspective too. It
will help us debug this NYC DSS issue hopefully.
N/A
N/A
> Add debug logging statement when logins are successful

- app/app/controllers/concerns/cbv/payments_helper.rb
- app/config/locales/en.yml
- app/spec/controllers/concerns/cbv/payments_helper_spec.rb
FFS 1166
* Update description language on summary page
* Fix missed net vs gross update
> summary page updates

- app/app/assets/stylesheets/cbv.scss
- app/app/helpers/application_helper.rb
- app/app/views/application/_footer.html.erb
- app/config/site-config.yml
- app/lib/site_config.rb
- app/spec/helpers/application_helper_spec.rb
Resolves FFS-1290.
I've hardcoded the link for now because from what I can tell, we have
only created one version of this form (not one per environment or site
or anything like that).
N/A
I clicked the link. It took me to the form.
> Link to bug reporting Google Form in footer

- app/app/controllers/application_controller.rb
- app/app/controllers/caseworker/cbv_flow_invitations_controller.rb
- app/app/controllers/caseworker/dashboards_controller.rb
- app/app/controllers/users/omniauth_callbacks_controller.rb
- app/app/views/caseworker/dashboards/show.html.erb
- app/config/locales/en.yml
- app/config/routes.rb
- app/db/schema.rb
- app/spec/controllers/caseworker/cbv_flow_invitations/auth_spec.rb
- app/spec/controllers/caseworker/cbv_flow_invitations/ma_spec.rb
- app/spec/controllers/caseworker/cbv_flow_invitations/nyc_spec.rb
- app/spec/controllers/caseworker/dashboards_controller_spec.rb
- app/spec/factories/user.rb
Resolves FFS-1299.
* Create a new page after the SSO but before the
/:site_id/invitations/new page.
* This page has some basic instructions for caseworkers, and a link to
the invitations screen.
N/A
Tested locally. Will acceptance test with Carmen.
> Implement caseworker /dashboard page

- app/app/controllers/application_controller.rb
N/A  - Noticed in live demo
Fixes i18n key.
N/A
N/A
> Fix incorrect I18n key for missing tokens

- .github/workflows/ci-docs.yml
- app/app/views/cbv/successes/show.html.erb
- app/config/locales/en.yml
Resolves FFS-1237.
Adds a redesigned /cbv/success page.
N/A
Tested locally.
> Implement designs for /cbv/success page

- app/app/views/cbv/payment_details/show.html.erb
- app/config/locales/en.yml
Resolves FFS-1406.
Copy changes on payment details and summary pages.
N/A
Acceptance testing by Carmen.
> Make "90 days" and "gross income" more prominent

- app/app/javascript/controllers/cbv/employer_search.js
- app/app/views/cbv/employer_searches/_employer.html.erb
N/A - I had been meaning to do this for a while.
- **Disable `<button>`s on employer search after clicking**
- **Track Pinwheel error events in NewRelic**
https://github.com/user-attachments/assets/f155e321-adb8-4fe9-b99a-a7cd7baf4eb0
We already have NewRelic installed, we may as well use it.
Tested locally, for both.
> Two improvements to employer search JS

- app/config/environments/production.rb
N/A
This will be necessary for deploys to succeed.
N/A
N/A
> Exclude /health from host verification

- app/package-lock.json
> Update package-lock.json for micromatch update

- app/app/views/cbv/employer_searches/_employer.html.erb
Resolves FFS-1438.
Oops, an off-by-1 error!
N/A
Tested locally, it works.
> Fix employer search fallback to show up with exactly 1 result

- app/package-lock.json
N/A - Fixes security alert.
Fixes security alert.
N/A
Tested that assets build locally - they do.
> Upgrade webpack 5.91.0 -> 5.94.0

- app/app/controllers/api/pinwheel_controller.rb
- app/app/controllers/application_controller.rb
- app/app/controllers/cbv/employer_searches_controller.rb
- app/app/controllers/cbv/payment_details_controller.rb
- app/config/newrelic.yml
- app/spec/controllers/api/pinwheel_controller_spec.rb
- app/spec/controllers/cbv/employer_searches_controller_spec.rb
- app/spec/controllers/cbv/payment_details_controller_spec.rb
- app/spec/support/pinwheel_api_helper.rb
Resolves FFS-1484.
- **Track NewRelic event when an employer search is conducted**
- **Track NewRelic event when employer link begins**
- **Track NewRelic events for viewing and saving payment details**
- **Set custom attributes in NewRelic APM**
N/A
Unit tests + tested the flow locally.
> Track 3 new NewRelic events

- app/app/views/cbv/summaries/show.pdf.erb
- app/config/locales/en.yml
Resolves [1146](https://jiraent.cms.gov/browse/FFS-1146)
Fixes some small content and design issues
https://nava.slack.com/archives/C05TH1SNJDS/p1725558871574379?thread_ts=1725397765.766009&cid=C05TH1SNJDS
> 1146: PDF feedback

- app/config/site-config.yml
N/A - Just for bug bash tomorrow.
In order for us to test MA in demo, let's temporarily replace its
configuration with sandbox.
N/A
N/A
> Temporarily replace MA configuration to match sandbox

- app/config/site-config.yml
N/A
This reverts commit 5bb623dc3914a554e2407abde5355f9494574b63.
This change was originally made only for testing during the bug bash on Friday.
N/A
> Revert "Temporarily replace MA configuration to match settings"

- app/config/locales/en.yml
Resolves [FFS-1412](https://jiraent.cms.gov/browse/FFS-1412)
> 1412: Removed the first sentence from case_number invalid_format error

- app/Dockerfile
n/a
Addressing security scan concerns
- Updated libpq postgres client for c [patch]
- Updated standard c binaries [patch] …
> Security - Patching postgres and c dependencies

- app/config/puma.rb
Relates to [FFS-2175](https://jiraent.cms.gov/browse/FFS-2175).
More info [here](https://github.com/puma/puma#clustered-mode)
* Make sure to notify the team once this PR is merged so we don't inadvertently deploy the unaccepted change to production. (e.g. `:alert: Deploy block! @ffs-eng I …
> FFS-2175 - Updating Puma webserver to preload the app

- app/config/site-config.yml
- app/spec/controllers/caseworker/cbv_flow_invitations_controller/auth_spec.rb
- app/spec/controllers/caseworker/cbv_flow_invitations_controller/nyc_spec.rb
- app/spec/controllers/caseworker/entries_controller_spec.rb
Resolves [FFS-2261](https://jiraent.cms.gov/browse/FFS-2261).
Disables staff portal for NYC
We will need to deploy this on the 24th but not before.
* Make sure to notify the team once this PR is merged so we don't inadvertently deploy the unaccepted change to production. (e.g. `:alert: Deploy …
> FFS-2261: Disable NYC Staff Portal

- app/app/views/cbv/expired_invitations/show.html.erb
- app/app/views/pages/home.html.erb
- app/config/i18n-tasks.yml
- app/config/locales/en.yml
- app/config/locales/es.yml
Resolves 2374
Updates copy for welcome and expired pages
I think the expired invite view is broken.
* Make sure to notify the team once this PR is merged so we don't inadvertently deploy the unaccepted change to production. (e.g. `:alert: Deploy block! @ffs-eng I just merged PR [#123] and …
> 2374: Include new wind down copy

- infra/app/app-config/dev.tf
- infra/app/app-config/prod.tf
No ticket.
* Demo: 3 x 4GB --> 1 x 2GB container
* Prod: 3 x 4GB --> 1 x 2GB container
We can easily scale back up when pilots are about to start back up by
reverting this commit. …
> Reduce number of containers in demo/prod while pilots are inactive

- .grype.yml
No ticket.
This dependency is used to build our javascript bundle, and has often
triggered false-alarm security alerts for whatever version of Go it was
built with.
Since this dependency is far out of the critical path for user traffic,
let's disable alerts for its vulnerabilities.
* Make …
> Ignore vulnerability scan issues in esbuild

- app/lib/tasks/users.rake
- app/spec/lib/users_rake_spec.rb
[FFS-2403](https://jiraent.cms.gov/browse/FFS-2403)
Adds a rake task to promote certain users to service account users and return their API keys
We don't have a way to do this in any deployed environment, even through rails console, afaict!
* Make sure to notify the team once this PR is …
> FFS-2403: Add service account promotion rake task

- app/Gemfile.lock
> Upgrade rack 2.2.10 -> 2.2.11

- app/app/javascript/adapters/ModalAdapter.ts
- app/app/javascript/adapters/ModalAdapter.types.ts
- app/app/javascript/adapters/PinwheelModalAdapter.ts
- app/app/javascript/types/Pinwheel.d.ts
- app/app/javascript/types/global.d.ts
- app/app/javascript/types/load-script.d.ts
- app/app/javascript/utilities/createModalAdapter.ts
Resolves [FFS-2464](https://jiraent.cms.gov/browse/FFS-2464).
Makes spacing conssitent with style of other files (2 space). …
> FFS-2464: Fix spacing formating

- app/lib/generic_event_tracker.rb
Reverts DSACMS/iv-cbv-payroll#466
> Revert "FFS-2397-2: use remote_ip instead of ip"

- app/Gemfile.lock
Addresses CVE-2025-27221.
* Upgrade uri 0.13.0 -> 1.0.3
N/A
* Make sure to notify the team once this PR is merged so we don't inadvertently deploy the unaccepted change to production. (e.g. `:alert: Deploy block! @ffs-eng I just merged PR [#123] and will be doing acceptance testing in demo - …
> Upgrade uri 0.13.0 -> 1.0.3

- .grype.yml
- app/Gemfile
- app/Gemfile.lock
Fixes GHSA-mhwm-jh88-3gjf.
* Upgrade cgi 0.4.1 -> 0.4.2
* Make sure to notify the team once this PR is merged so we don't inadvertently deploy the unaccepted change to production. (e.g. `:alert: Deploy block! @ffs-eng I just merged PR [#123] and will be doing acceptance testing in demo - …
> Upgrade cgi 0.4.1 -> 0.4.2

- app/app/javascript/utilities/createModalAdapter.ts
- app/app/views/cbv/employer_searches/show.html.erb
No ticket - bug I noticed during dev.
* **Fix default /employer_search options**
The default providers/employers were broken. They need a `data-provider-name`
attribute, as the search results have, so the correct modal can be launched.
* Make sure to notify the team once this PR is merged so …
> Fix default /employer_search options

- app/app/services/argyle_service.rb
Fixes 404 error message on argyle user token method due to an improper "/" at the start of the path. 
* Make sure to notify the team once this PR is merged so we don't inadvertently deploy the unaccepted change to production. (e.g. `:alert: Deploy block! @ffs-eng I just merged PR [#123] and …
> Fixes 404 issue with argyle service due to improper path

- app/Gemfile.lock
n/a
Resolves the following rack vulnerability
```
NAME  INSTALLED  FIXED-IN  TYPE  VULNERABILITY        SEVERITY 
rack  2.2.12     2.2.[13](https://github.com/DSACMS/iv-cbv-payroll/actions/runs/13818198201/job/38656793996?pr=502#step:4:14)    gem   GHSA-7wqh-767x-r66v  High
```
* Make sure to …
> Patch - Rack -> 2.2.13

- .github/reviewer-lottery.yml
- .github/workflows/pr-reviewer-lottery.yml
N/A - See [Slack](https://cmsgov.slack.com/archives/C066XS5543S/p1741799002847639).
* Add GH Action to automatically choose a random reviewer
I found [this GH Action][1] via Google which picks a random reviewer
whenever a PR is opened or marked "ready for review". Seems worth a try?
As it is not very heavily utilized, I skimmed its source code and didn't
see anything alarming.
[1]: https://github.com/marketplace/actions/reviewer-lottery
* Acceptance testing should be done by **design** for visual changes, **product** for behavior/logic changes, **or both** …
> Add GH Action to automatically choose a random reviewer

- app/Dockerfile
N/A - Fixes system dependency scans.
There must have been an update to the Debian package repos,
necessitating the upgrade of:
1. git
2. libpq-dev
3. curl
In addition, the following upgrades are necessary for addressing
CVE-2025-0395:
4. linux-libc-dev
5. libc-dev
6. libc-dev-bin
* Make sure …
> Bump six system dependency versions

- app/package-lock.json
N/A - Vulnerability Scan finding.
* Upgrade vite 6.1.0 -> 6.2.3
This addresses a vulnerability scan in vite, a dependency of our
JavaScript testing framework (vitest).
* Make sure to notify the team once this PR is merged so we don't inadvertently deploy the unaccepted change to production. …
> Upgrade vite 6.1.0 -> 6.2.3

- README.md
- app/.env
- app/config/initializers/wicked_pdf.rb
N/A
Setting this env var to "true" will allow development on platforms not
explicitly supported by the `wkhtmltopdf-binary` gem. (In Cle's case,
Ubuntu 24).
This also improves the documentation and structure of the .env file
somewhat.
I put this in a Gist for Cle'. I may as well just commit it so it's one less
thing for him to sort out in his development environment.
* This change is hard to test locally, so …
> Add USE_SYSTEM_WKHTMLTOPDF override for Cle

- app/package-lock.json
N/A - Vulnerability scan.
* Upgrade tar-fs 2.1.1 -> 2.1.2
Fixes GHSA-pq67-2wwv-3xjx.
* Make sure to notify the team once this PR is merged so we don't inadvertently deploy the unaccepted change to production. (e.g. `:alert: Deploy block! @ffs-eng I just merged PR [#123] and will be doing …
> Upgrade tar-fs 2.1.1 -> 2.1.2

- app/package-lock.json
N/A
Addresses GHSA-4r4m-qw57-chr8.
* Make sure to notify the team once this PR is merged so we don't inadvertently deploy the unaccepted change to production. (e.g. `:alert: Deploy block! @ffs-eng I just merged PR [#123] and will be doing acceptance testing in demo - please don't deploy until …
> Upgrade vite 6.2.3 -> 6.2.4

- CODEOWNERS.md
- OUTSIDE_COLLABORATORS.md
Add DSAC outside collaborator process in case of account loss, update CODEOWNERS.md file
> add outside collab DSAC process document, update code owners

- app/Dockerfile
- app/package-lock.json
N/A - Vulnerability scan.
- **Upgrade vite 6.2.4 -> 6.2.5**
- **Upgrade liblzma5**
* Make sure to notify the team once this PR is merged so we don't inadvertently deploy the unaccepted change to production. (e.g. `:alert: Deploy block! @ffs-eng I just merged PR [#123] and will be doing …
> Address security vulnerabilities in vite and liblzma5

- .github/reviewer-lottery.yml
Resolves [FFS-XXXX](https://jiraent.cms.gov/browse/FFS-XXXX).
* Make sure to notify the team once this PR is merged so we don't inadvertently deploy the unaccepted change to production. (e.g. `:alert: Deploy block! @ffs-eng I just merged PR [#123] and will be doing acceptance testing in demo …
> Remove Cle from PR review lottery

- app/app/controllers/webhooks/argyle/events_controller.rb
- app/app/controllers/webhooks/pinwheel/events_controller.rb
- app/app/services/aggregators/aggregator_reports/pinwheel_report.rb
- app/app/services/aggregators/response_objects/earning.rb
- app/app/services/aggregators/response_objects/identity.rb
- app/app/services/aggregators/response_objects/paystub.rb
- app/spec/controllers/webhooks/argyle/events_controller_spec.rb
- app/spec/controllers/webhooks/pinwheel/events_controller_spec.rb
- app/spec/rails_helper.rb
- app/spec/services/aggregators/aggregator_reports/pinwheel_report_spec.rb
- app/spec/services/aggregators/response_objects/identity_spec.rb
- app/spec/services/aggregators/response_objects/paystub_spec.rb
Resolves [FFS-2501](https://jiraent.cms.gov/browse/FFS-2501).
Pinwheel:
Argyle:
- **Add fields for DOB/Email/SSN/Phone to ResponseObjects::Identity**
- **Track which fields reports contain when they finish syncing** …
> FFS-2501: Track analytics of payroll aggregator fields

- infra/app/app-config/dev.tf
- infra/app/app-config/prod.tf
N/A - This will be necessary/useful for load testing.
Now that Phase 2 pilots are more imminent, the time for trying to penny
pinch on infrastructure costs is over.
This reverts commit 107a01e33a3522e513ead47d63ec1140529436d1. …
> Increase number of containers in demo/prod

- infra/app/app-config/env-config/environment-variables.tf
N/A - Necessary for Argyle sync.
The Argyle webhooks are currently failing because ARGYLE_WEBHOOK_SECRET
is nil. Let's add these variables to terraform so we can define them
within AWS CLI.
* Make sure to notify the team once this PR is merged so we don't inadvertently deploy the unaccepted …
> Add terraform for 4 Argyle environment variables

- app/Dockerfile
- app/package-lock.json
bumping linux-libc-dev and vite to fix CVEs
* Make sure to notify the team once this PR is merged so we don't inadvertently deploy the unaccepted change to production. (e.g. `:alert: Deploy block! @ffs-eng I just merged PR [#123] and will be doing acceptance testing in demo - please don't …
> No ticket: bumping linux-libc-dev and vite to fix CVEs

- app/app/services/aggregators/aggregator_reports/aggregator_report.rb
- app/app/services/aggregators/aggregator_reports/argyle_report.rb
- app/app/services/aggregators/aggregator_reports/pinwheel_report.rb
- app/app/services/aggregators/response_objects/employment.rb
- app/spec/controllers/cbv/payment_details_controller_spec.rb
- app/spec/services/aggregators/aggregator_reports/argyle_report_spec.rb
- app/spec/support/fixtures/pinwheel/request_end_user_no_paystubs_response.json
- app/spec/support/pinwheel_api_helper.rb
N/A - Breaking out some fixes I made for #560.
- **Use correct field for employer_name**
- **Minor formatting updates**
- **Update PaymentDetailsController spec back to using request stubs**
See commit messages for context. …
> Fix employment_type bug and update specs

- infra/app/app-config/env-config/environment-variables.tf
n/a
The environment variable `AZ_DES_PINWHEEL_ENVIRONMENT` was missing from our Terraform config
* Make sure to notify the team once this PR is merged so we don't inadvertently deploy the unaccepted change to production. (e.g. `:alert: Deploy block! @ffs-eng I just merged PR [#123] and will …
> Added AZ_DES_PINWHEEL_ENVIRONMENT to terraform environment-variables.tf

- app/app/helpers/cbv/aggregator_data_helper.rb
- app/app/services/aggregators/aggregator_reports/composite_report.rb
- app/spec/controllers/cbv/summaries_controller_spec.rb
- app/spec/factories/payroll_account.rb
- app/spec/services/aggregators/aggregator_reports/composite_report_spec.rb
Resolves [FFS-2777](https://jiraent.cms.gov/browse/FFS-2777).
Fixes a couple bugs in the CompositeReport:
* Forgetting a `.new`
* Rewriting `earlier_date`/`later_date` so they don't `Date.parse` an existing date
* Writing specs, including a test factory for Argyle bob.
* Make sure to notify …
> FFS-2777: Fix CompositeReport on /summary and PDF rendering

- .github/workflows/pr-reviewer-lottery.yml
N/A - Fixes regression.
Remove the conditional logic. It's not working for some reason (it results in
the job always being skipped). I tried debugging it for 15 minutes, to no
avail, so let's just remove it.
This reverts commit f7cbef7c44e2b965b949d5a384bcacd108fb813d.
* Make sure to notify …
> Fix reviewbot by removing conditional logic

- load_testing/README.md
- load_testing/docker-compose.yml
- load_testing/loadtest.js
Introduces a methodology for running load testing.
Start with being able to run a battery of load tests locally, pointed against the desired target environment.
Tests ran with 3 demo servers:
* 2 concurrent users
* 500 concurrent users
* 2000 concurrent users
* at 2 requests simultaneously, you've got median response time of about 10ms with 10% of users experiencing 30 ms.
* at 500 requests simultaneously, you've got a median response time of about 40 ms, but with 10% of users experiencing 4 second delays on requests. About 1-5% of requests drop on the floor.
* at 2000 requests simultaneously, you've got median response time of about 40ms, but 10% of users experience 42 second delays on requests. About 10-20% of requests also drop on the floor.
* all of these requests perform about …
> FFS-2638: introduce load testing and first round of results

- app/app/controllers/application_controller.rb
- app/config/application.rb
- app/config/client-agency-config.yml
- app/config/environments/production.rb
- app/config/environments/test.rb
- app/lib/client_agency_config.rb
- app/spec/controllers/application_controller_spec.rb
Resolves [FFS-2693](https://jiraent.cms.gov/browse/FFS-2693).
* Make sure to notify the team once this PR is merged so we don't inadvertently deploy the unaccepted change to production. (e.g. `:alert: Deploy block! @ffs-eng I just merged PR [#123] and will be doing acceptance testing in demo …
> FFS-2693 - Enable client agency resolution via request Host

- app/app/mailers/caseworker_mailer.rb
- app/config/i18n-tasks.yml
- app/config/locales/en.yml
- app/spec/mailers/caseworker_mailer_spec.rb
Resolves [FFS-2695](https://jiraent.cms.gov/browse/FFS-2695).
- Agency config for caseworker mailer email subject line
- Custom subject for LA
- Testing
* Make sure to notify the team once this PR is merged so we don't inadvertently deploy the unaccepted change to production. (e.g. `:alert: …
> FFS-2695: Set report delivery email subject line to "CBV Report"

- app/config/i18n-tasks.yml
- app/config/locales/en.yml
- app/config/locales/es.yml
Implemented LA copy for /add_jobs
Removed ma/nyc copy for /add_jobs
2. Go through the workflow to /add_jobs
3. Verify the copy matches [the design](https://confluenceent.cms.gov/pages/viewpage.action?pageId=748887627) …
> FFS-2688-add_jobs: implemented add_jobs copy changes

- app/Dockerfile
N/A - This is needed for the build to succeed.
* Make sure to notify the team once this PR is merged so we don't inadvertently deploy the unaccepted change to production. (e.g. `:alert: Deploy block! @ffs-eng I just merged PR [#123] and will be doing acceptance testing in demo - please don't …
> Fix missing linux-libc-dev version

- app/spec/models/payroll_account/argyle_spec.rb
N/A - Tiny cleanup.
The tests for `#necessary_jobs_succeeded?` and `#job_succeeded?` were
accidentally nested within the tests for `#has_fully_synced?`. Oops.
* Make sure to notify the team once this PR is merged so we don't inadvertently deploy the unaccepted change to production. (e.g. …
> Fix indenting in PayrollAccount::Argyle spec

- infra/networks/deprecated_domains.tf
N/A - Issue from deploying terraform in #599 .
* Make sure to notify the team once this PR is merged so we don't inadvertently deploy the unaccepted change to production. (e.g. `:alert: Deploy block! @ffs-eng I just merged PR [#123] and will be doing acceptance testing in demo - please don't …
> Add conditionals to deprecated resources

- app/config/environments/production.rb
- infra/app/service/deprecated_domains.tf
Co-Authored-By: tomdooner@navapbc.com
* Make sure to notify the team once this PR is merged so we don't inadvertently deploy the unaccepted change to production. (e.g. `:alert: Deploy block! @ffs-eng I just merged PR [#123] and will be doing acceptance testing in demo - please don't deploy …
> Update terraform alias for snap-income-pilot.com

- app/app/views/maintenance/show.html.erb
- app/config/i18n-tasks.yml
- app/config/locales/en.yml
- app/config/locales/es.yml
Implemented LA copy for /maintenance
Updated page header for all pages
1. Use [this link](http://localhost:3000/maintenance) to view the maintenance page
2. Verify the copy matches [the design](https://confluenceent.cms.gov/pages/viewpage.action?pageId=780014728)
* Make sure to notify the …
> FFS-2688-maintenance: content updates for LA

- app/app/views/cbv/missing_results/show.html.erb
- app/config/i18n-tasks.yml
- app/config/locales/en.yml
- app/config/locales/es.yml
Implemented LA copy for /missing_results
2. Proceed to the employer_searches page, search for something, then click "I can't find my company or payroll provider"
3. Verify the copy matches [the design](https://confluenceent.cms.gov/pages/viewpage.action?pageId=753670824)
4. Go back to employer_searches, attach a provider, go through the flow but go back to employer_searches, then click "I can't find my company or payroll provider"
5. Verify the copy matches again, but this time for when you have an employer linked
* This change can be verified visually via screenshots attached below or by sending a link …
> FFS-2688-missing_results: updated content for LA

- app/app/views/cbv/submits/show.html.erb
- app/config/i18n-tasks.yml
- app/config/locales/en.yml
- app/config/locales/es.yml
Implemented LA copy for /submit
Removed ma/nyc strings
2. Proceed through the flow to the /submit page
3. Verify the copy matches [the design](https://confluenceent.cms.gov/pages/viewpage.action?pageId=932554140) …
> FFS-2688-submit: implemented LA copy changes

- app/app/views/cbv/successes/show.html.erb
- app/config/i18n-tasks.yml
- app/config/locales/en.yml
- app/config/locales/es.yml
Implemented LA copy for /success
Removed ma/nyc strings
2. Proceed through the flow to the /success page
3. Verify the copy matches [the design](https://confluenceent.cms.gov/pages/viewpage.action?pageId=748887629) …
> FFS-2688-success: implemented LA copy

- app/app/views/cbv/applicant_informations/_la_ldh.html.erb
- app/app/views/cbv/applicant_informations/show.html.erb
- app/config/i18n-tasks.yml
- app/config/locales/en.yml
- app/config/locales/es.yml
Implemented LA copy for /applicant_information
2. Proceed through the flow to the /applicant_information page. Note that there is a bug preventing this screen from showing in the normal flow; when you're on the /summary page, click the Edit link to be taken to the correct page.
3. Verify the copy matches [the design](https://confluenceent.cms.gov/pages/viewpage.action?pageId=954271085)
* Acceptance testing should be done by **design** for visual changes, …
> FFS-2688-applicant_information: implemented LA copy

- app/app/views/pages/home.html.erb
- app/config/i18n-tasks.yml
- app/config/locales/en.yml
- app/config/locales/es.yml
Implemented LA copy for /welcome
1. Use [this link](http://localhost:3000/) to access the welcome page
2. Verify the copy matches [the design](https://confluenceent.cms.gov/pages/viewpage.action?pageId=769722831)
3. This ticket also is responsible for updating the timeout page, but no changes to copy were necessary. If you want to verify that, use [this link](http://localhost:3000/en/cbv/links/la_ldh) to kick off the generic link flow for LA and let it time out.
* Acceptance testing should be done by **design** for visual changes, **product** for …
> FFS-2688-welcome: implemented LA copy

- app/app/helpers/report_view_helper.rb
- app/app/views/cbv/submits/show.pdf.erb
- app/config/i18n-tasks.yml
- app/config/locales/en.yml
- app/config/locales/es.yml
- app/spec/components/aggregate_data_point_component_spec.rb
Implemented LA copy for the client pdf
2. You will need to test multiple [personas](https://confluenceent.cms.gov/display/SFIV/Additional+Argyle+Sandbox+Test+Users) to see all the copy changes. I suggest andy_doe for a W2 worker with data and normula_doe for a gig worker with no data
3. Proceed through the flow to the /success page and download your PDF
4. Verify the copy matches [the design](https://confluenceent.cms.gov/pages/viewpage.action?pageId=753664031)
* This change can be verified visually via screenshots attached below or by sending a link to a local development environment to the acceptance …
> FFS-2688-client_pdf: implemented LA copy

- app/package-lock.json
- app/package.json
n/a
* Make sure to notify the team once this PR is merged so we don't inadvertently deploy the unaccepted change to production. (e.g. `:alert: Deploy block! @ffs-eng I just merged PR [#123] and will be doing acceptance testing in demo - please don't deploy until I'm finished!`)
> Security update - Address Vite vulnerability GHSA-859w-5945-r5v3

- app/app/views/cbv/summaries/show.html.erb
- app/config/i18n-tasks.yml
- app/config/locales/en.yml
- app/config/locales/es.yml
- app/spec/controllers/cbv/summaries_controller_spec.rb
Implemented LA copy for /summary
Removed unused strings
2. You will need to test multiple [personas](https://confluenceent.cms.gov/display/SFIV/Additional+Argyle+Sandbox+Test+Users) to see all the copy changes. I suggest andy_doe for the W2 worker with data, normula_doe for a gig worker with no data (sign up with Uber to get gig data)
3. Proceed through the flow to the /summary page
4. Verify the copy matches [the design](https://confluenceent.cms.gov/pages/viewpage.action?pageId=748887624)
* This change can be verified visually via screenshots attached below or by sending a link to a local development …
> FFS-2688: implemented copy changes for /summary

- app/app/controllers/webhooks/argyle/events_controller.rb
- app/app/controllers/webhooks/pinwheel/events_controller.rb
- app/bin/will-deploy
- app/spec/controllers/webhooks/argyle/events_controller_spec.rb
- app/spec/controllers/webhooks/pinwheel/events_controller_spec.rb
N/A - Followup after FFS-2829.
The four improvements mentioned are:
- **Rename ApplicantReceivedArgyleData `sixty_days` -> `ninety_days`**
- **Limit ApplicantFinishedArgyleSync to only track once**
- **Add argyle/pinwheel environment to sync events**
- **Add ID attributes to ApplicantReportMetUsefulRequirements events**
There is also one unrelated change included here out of convenience:
- **Update bin/will-deploy to tag the correct slack group**
* Acceptance testing should be done by **design** for visual changes, **product** for behavior/logic changes, …
> Make four improvements to Argyle/Pinwheel sync events

- app/app/controllers/webhooks/argyle/events_controller.rb
- app/app/controllers/webhooks/pinwheel/events_controller.rb
- app/app/models/payroll_account/pinwheel.rb
- app/spec/controllers/webhooks/argyle/events_controller_spec.rb
- app/spec/controllers/webhooks/pinwheel/events_controller_spec.rb
Resolves [FFS-2827](https://jiraent.cms.gov/browse/FFS-2827).
**FFS-2827: Log /gigs and /shifts analytics for Pinwheel and Argyle**
* Make sure to notify the team once this PR is merged so we don't inadvertently deploy the unaccepted change to production. (e.g. `:alert: Deploy block! @ffs-eng …
> FFS-2827: Log /gigs and /shifts analytics for Pinwheel and Argyle

- app/app/services/pinwheel_webhook_manager.rb
N/A - Failure observed while deploying.
Commit 5fb2ac3 added the logic for handling this webhook, but I
accidentally assumed that adding it to
PayrollAccount::Pinwheel::JOBS_TO_WEBHOOK_EVENTS would result in it
automatically being subscribed to via PinwheelWebhookManager.
* Make sure to …
> Subscribe to missing pinwheel webhook (shifts.added)

- app/app/models/payroll_account/pinwheel.rb
- app/spec/models/payroll_account/pinwheel_spec.rb
N/A - Bugfix for Pinwheel in demo.
Commit 5fb2ac3 added this logic to the has_fully_synced? method, but it
had a typo in a mismatch of the name of the job and the webhook event.
Regression test included, and I manually verified it this time.
* Make sure to notify the team once this PR is …
> Fix pinwheel sync on shifts/gigs endpoint

- app/app/views/cbv/add_jobs/show.html.erb
- app/app/views/cbv/employer_searches/_employer.html.erb
- app/app/views/cbv/employer_searches/show.html.erb
- app/app/views/cbv/entries/show.html.erb
- app/app/views/cbv/expired_invitations/show.html.erb
- app/app/views/cbv/missing_results/show.html.erb
- app/app/views/cbv/synchronization_failures/show.html.erb
- app/config/client-agency-config.yml
- app/config/i18n-tasks.yml
- app/config/locales/en.yml
- app/config/locales/es.yml
Various fixes found during AC testing of other copy update PRs. These include:
1. In LA, we should not say "Medicaid application" but instead "Medicaid benefits". This has been changed on /applicant_information, /payment_details, the PDF, and /success.
2. In the configs, I had left an old URL for Louisiana's website. But in addition to correcting that, I've updated all the string tokens to load the URL from settings instead of hardcoding it. There is now one exception: the URL on the /entry page should still go to mymedicaid.la.gov. 
3. On /entry, you should now be able to open both of the accordions at the bottom of the screen at the same time. Before, when you opened one, the other would close.
4. On the help modal under the company ID option, we had abbreviated "info" but it is now the …
> FFS-2688: Various fixes

- app/config/database.yml
Performance testing in FFS-2818.
We're trying this to see if it improves concurrency.
* Make sure to notify the team once this PR is merged so we don't inadvertently deploy the unaccepted change to production. (e.g. `:alert: Deploy block! @ffs-eng I just merged PR [#123] and will be doing …
> Allow 2 * RAILS_MAX_THREADS connections to database

- app/Gemfile.lock
Fix the below vulnerabilities:
NAME  INSTALLED  FIXED-IN  TYPE  VULNERABILITY        SEVERITY 
rack  2.2.13     2.2.14    gem   GHSA-gjh7-p2fx-99vx  High      
rack  2.2.13     2.2.14    gem   GHSA-vpfw-47h7-xj4g  Medium …
> Security upgrade rack from 2.2.13 to 2.2.14

- app/.env
- app/config/client-agency-config.yml
- infra/app/app-config/env-config/environment-variables.tf
Resolves [FFS-2847](https://jiraent.cms.gov/browse/FFS-2847).
**FFS-2847: Create env var for LA report recipient email**
> This is necessary to send them to the proper email inbox, not just our
> test email.
* Make sure to notify the team once this PR is merged so we don't inadvertently …
> FFS-2847: Create env var for LA report recipient email

- app/app/controllers/webhooks/argyle/events_controller.rb
- app/app/controllers/webhooks/pinwheel/events_controller.rb
- app/spec/controllers/webhooks/argyle/events_controller_spec.rb
Resolves [FFS-2834](https://jiraent.cms.gov/browse/FFS-2834).
Eryn noticed this bug during acceptance testing. :man_facepalming:
* Make sure to notify the team once this PR is merged so we don't inadvertently deploy the unaccepted change to production. (e.g. `:alert: Deploy block! @ffs-eng I …
> FFS-2834: Fix calculation of median for W-2 hours/gross_pay_amount

- app/app/views/cbv/payment_details/show.html.erb
- app/spec/controllers/cbv/payment_details_controller_spec.rb
- app/spec/support/fixtures/pinwheel/request_end_user_paystubs_response.json
Resolves [FFS-2869](https://jiraent.cms.gov/browse/FFS-2869).
- Cast nil to float to fix equality error
- Test
* Make sure to notify the team once this PR is merged so we don't inadvertently deploy the unaccepted change to production. (e.g. `:alert: Deploy block! @ffs-eng I just merged PR …
> FFS-2869: Fix 'undefined method `>' for nil' error on /payment_details

- infra/app/app-config/env-config/environment-variables.tf
Related to [FFS-2873](https://jiraent.cms.gov/browse/FFS-2873).
* **Increase RAILS_MAX_THREADS from 5 -> 10**
In deployed environments, having 10 threads allows us to serve much more
load reliably.
See - https://cmsgov.slack.com/archives/C08BBUALWQN/p1747185382465289?thread_ts=1747086327.646649&cid=C08BBUALWQN …
> Increase RAILS_MAX_THREADS from 5 -> 10

- load_testing/README.md
- load_testing/loadtest.js
Resolves [FFS-2873](https://jiraent.cms.gov/browse/FFS-2873).
**FFS-2873: Update load testing script with new SLOs/user model**
* Make sure to notify the team once this PR is merged so we don't inadvertently deploy the unaccepted change to production. (e.g. `:alert: Deploy block! @ffs-eng I …
> FFS-2873: Update load testing script with new SLOs/user model

- app/app/controllers/api/argyle_controller.rb
- app/app/services/aggregators/webhooks/argyle.rb
- app/spec/controllers/api/argyle_controller_spec.rb
- app/spec/controllers/webhooks/argyle/events_controller_spec.rb
- app/spec/factories/cbv_flow.rb
- app/spec/factories/payroll_account.rb
- app/spec/support/argyle_api_helper.rb
N/A
I am performing these tests to verify correctness:
* Make sure to notify the team once this PR is merged so we don't inadvertently deploy the unaccepted change to production. (e.g. `:alert: Deploy block! @ffs-eng I just merged PR [#123] and will be doing acceptance testing in demo - …
> FFS-2867: Fix incorrect credentials Arygle modal not reopening

- app/app/views/cbv/synchronization_failures/show.html.erb
Resolves [FFS-2878](https://jiraent.cms.gov/browse/FFS-2878).
**FFS-2878: Take user to /applicant_informations after sync fail**
> Commit eebb0e3 updated the /missing_results page to take the user to the
> /applicant_informations page (if they had previously linked a payroll
> account).
> We need to also do this on /synchronization_failures, as it's the other
> place we redirect people forward in the flow.
* …
> FFS-2878: Take user to /applicant_informations after sync fail

- app/app/models/cbv_applicant.rb
- app/config/client-agency-config.yml
> Removing some non-functional code and fixing a typo

- app/Dockerfile
- app/app/views/cbv/submits/show.pdf.erb
- app/spec/controllers/cbv/submits_controller_spec.rb
- app/spec/controllers/webhooks/argyle/events_controller_spec.rb
- app/spec/support/fixtures/argyle/sarah/request_paystubs.json
Hotfix.  Resolves same issue from [FFS-2869](https://jiraent.cms.gov/browse/FFS-2869) on the /submit page.
* Cast nil to float to fix equality error
* Test
* Also, upgraded libpq-dev to 15.13-0+deb12u1  and openssl to 3.0.16-1~deb12u1
* Make sure to notify the team once this PR is merged so …
> Fix 'undefined method `>' for nil' error on /submits

- app/app/services/aggregators/aggregator_reports/aggregator_report.rb
- app/spec/services/aggregators/aggregator_reports/aggregator_report_spec.rb
Resolves [FFS-2925](https://jiraent.cms.gov/browse/FFS-2925).
- We can't sum nil, so if it's nil, use 0 instead
- Test
Please see [New Relic error logs](https://one.newrelic.com/nr1-core/errors-inbox/entity-inbox/NDYxOTY3NnxBUE18QVBQTElDQVRJT058MTMwMTU0Njg4MQ?duration=1800000&filters=selectedInstance%20IN%20%28%29&state=95d75c15-80db-b346-8dd5-db02498bdb34)
* This change is hard to test locally, so we'll …
> FFS-2925: nil can't be coerced into Integer

- .github/workflows/vulnerability-scans.yml
- .grype.yml
- .trivyignore
- app/.dockerignore
- app/Dockerfile
- bin/lint-markdown
- docs/infra/vulnerability-management.md
- load_testing/README.md
> Upgrade linux-libc-dev to address security vulnerability

- app/spec/mailers/applicant_mailer_spec.rb
- app/spec/mailers/previews/applicant_mailer_preview.rb
- app/spec/mailers/previews/caseworker_mailer_preview.rb
- app/spec/mailers/previews/weekly_report_mailer_preview.rb
- app/spec/mailers/weekly_report_mailer_spec.rb
Resolves [FFS-2572](https://jiraent.cms.gov/browse/FFS-2572).
I fixed the date error in the weekly report that was keeping it from loading. Removed some unused nyc/ma code, although that does hide some of our patterns for how to create mailers. I propose we have a ticket to update these every time we take on a new pilot (with all the rest of cleanup). Each agency should have its own clickable button on the mailer page for each case.
Not perfect, but an improvement?
* Acceptance testing should be done by **design** for visual changes, **product** for …
> FFS-2572: Our mailer testers are broken

- infra/app/app-config/env-config/scheduled_jobs.tf
Follow-up to [FFS-2863](https://jiraent.cms.gov/browse/FFS-2863).
* Fix syntax of the cron job
* Make sure to notify the team once this PR is merged so we don't inadvertently deploy the unaccepted change to production. (e.g. `:alert: Deploy block! @ffs-eng I just merged PR [#123] and will be …
> Fix cron expression for AWS `send_queue_metrics` job

- infra/app/app-config/prod.tf
N/A
* Decreases number of containers and DB size
* Make sure to notify the team once this PR is merged so we don't inadvertently deploy the unaccepted change to production. (e.g. `:alert: Deploy block! @ffs-eng I just merged PR [#123] and will be doing acceptance testing in demo - please …
> Scale down now that LA launch traffic has abated

- app/Dockerfile
N/A - Security scan
We had just upgraded it in 67e89e1, ugh. To prevent needing to
micromanage this version in the future, I moved it to the top list of
unpinned system packages. …
> Upgrade linux-libc-dev again to resolve security scan again

- app/config/client-agency-config.yml
Resolves [FFS-2663](https://jiraent.cms.gov/browse/FFS-2663).
**FFS-2663: Decrease AZ invitation_valid_days from 14 -> 10** …
> FFS-2663: Change AZ invitation_valid_days from 14 to 10

- .pre-commit-config.yaml
- app/app/views/cbv/employer_searches/_employer.html.erb
- app/app/views/cbv/missing_results/show.html.erb
- app/config/locales/en.yml
- app/config/locales/es.yml
N/A - Noticed this while reading through the code.
For AZ, this would break. This commit updates it to use the variables
called for in the content reference.
* Make sure to notify the team once this PR is merged so we don't inadvertently deploy the unaccepted change to production. (e.g. …
> Fix two translations on /employer_search to render for AZ DES

- app/package-lock.json
- app/package.json
n/a
Fix for vulnerability [GHSA-8cj5-5rvv-wf4v](https://github.com/DSACMS/iv-cbv-payroll/actions/runs/15452444875/job/43497554542?pr=723)
* Make sure to notify the team once this PR is merged so we don't inadvertently deploy the unaccepted change to production. (e.g. `:alert: Deploy block! …
> FFS-PATCH: Vulnerability GHSA-8cj5-5rvv-wf4v

- .github/workflows/cd-app.yml
- .github/workflows/deploy.yml
N/A - Bugfix for deploy process.
Commit 289e21c8 did this for a number of GH Actions, which worked, but
did not include the top-level `cd-app` one that is what triggers the
ultimate deploy.
* Make sure to notify the team once this PR is merged so we don't inadvertently deploy the unaccepted …
> Fix `deploy` GH Action by inheriting secrets too

- app/app/views/cbv/successes/show.html.erb
- app/config/i18n-tasks.yml
- app/config/locales/en.yml
- app/config/locales/es.yml
Implemented final internal pass on Spanish translations for AZ go-live
* Make sure to notify the team once this PR is merged so we don't inadvertently deploy the unaccepted change to production. (e.g. `:alert: Deploy block! @ffs-eng I just merged PR [#123] and will be doing acceptance testing …
> FFS-2953: implemented final Spanish translations

- app/app/components/table_row_component.rb
- app/spec/components/aggregate_data_point_component_spec.rb
Resolves [FFS-2999](https://jiraent.cms.gov/browse/FFS-2999).
* Fixed a mistake that caused highlight option to be ignored.  Added test.
* Make sure to notify the team once this PR is merged so we don't inadvertently deploy the unaccepted change to production. (e.g. `:alert: Deploy block! …
> FFS-2999: re-enable highlighting

- app/app/views/cbv/submits/show.pdf.erb
- app/config/locales/en.yml
- app/config/locales/es.yml
- app/spec/controllers/cbv/submits_controller_spec.rb
Half of [FFS-2999](https://jiraent.cms.gov/browse/FFS-2999).
**FFS-2999: Remove "Medicaid application date" from LA income report**
> We don't want to render this field for LA. Let's hide it as well. Since
> there was an agency-specific customization for LA, we can remove that
> customization.
* This change is hard to test locally, so we'll test it in the demo environment (deployed automatically after …
> FFS-2999: Remove "Medicaid application date" from LA income report

- app/.erb_lint.yml
- app/app/views/cbv/summaries/show.html.erb
N/A - Test failure introduced by #788, I think.
Erb-lint seems to be failing on a bunch of lint errors in vendor/bundle.
I suppose we need to configure erb_lint to ignore that directory.
* Make sure to notify the team once this PR is merged so we don't inadvertently deploy the unaccepted …
> Fix erb_lint inadvertently running on vendor/bundle files

- app/Dockerfile
N/A - Vulnerability Scan fixes
These are two system libraries that have CVEs.
Upgrading them in our base image should address the scan failures, until we get a newer base image that has their upgraded versions automatically. …
> Upgrade libxml and libicu to address vulnerabilities

- README.md
- app/Gemfile
- app/Gemfile.lock
Updates debase from 0.2.5.beta2 to 0.2.9
* Fixes compilation issues (see [release notes for 0.2.8](https://github.com/ruby-debug/debase/compare/0.2.7...0.2.8)) 
* Note: I have verified the install process on a fresh install on MacOS Sequoia and there is no longer a build error for debase
* …
> Update debase from 0.2.5.beta2 to 0.2.9

- .github/workflows/ci-app-pr-environment-checks.yml
- .github/workflows/ci-app-pr-environment-destroy.yml
- infra/app/service/deprecated_domains.tf
- infra/app/service/main.tf
- infra/app/service/newrelic.tf
- infra/modules/service/access-logs.tf
- infra/modules/service/dns.tf
- infra/modules/service/main.tf
- infra/modules/storage/lifecycle.tf
- infra/modules/terraform-backend-s3/main.tf
Resolves [FFS-1904](https://jiraent.cms.gov/browse/FFS-1904).
- Enable PR environments in GA
- Update Terraform to components to play nice with temporary environments
- Add `filter {}` to comply with newer Terraform version
- Pass AWS ALB DNS to `DOMAIN_NAME` for temp environments
I don't really think this needs acceptance testing, but I would like to confirm that it's accessible and works well for our team! …
> FFS-1904: Set up review apps to ease acceptance testing

- .github/workflows/ci-infra.yml
- .github/workflows/vulnerability-scans.yml
N/A - Fixes flaky build.
* **Upgrade `erzz/dockle-action` v1.3.1 -> v1.4.0**
* **Upgrade `aquasecurity/tfsec-pr-commenter-action` v1.2.0 -> v1.3.1**
**Upgrade `erzz/dockle-action` v1.3.1 -> v1.4.0**
We've been having intermittent issues with the older version, possibly
because the Dockle download fails.
The newer version uses the GH Auth token when downloading Dockle, which
should be less likely to be rate-limited.
Also, I've relaxed the version constraint here to take advantage of
other upgrades like this from the community.
**Upgrade `aquasecurity/tfsec-pr-commenter-action` v1.2.0 -> v1.3.1**
This newer version includes better support for using the Github Token on
all Github API requests involved in downloading tfsec (previously it was
only used in posting the comment itself).
* This …
> Upgrade `erzz/dockle-action` v1.3.1 -> v1.4.0

- app/app/controllers/api/argyle_controller.rb
- app/app/controllers/api/pinwheel_controller.rb
- app/app/controllers/feedbacks_controller.rb
N/A - Bugfixes noticed while perusing Mixpanel.
* Add to **ApplicantBeganLinkingEmployer** attributes that show which
item is attempted to be linked. We track this later in the flow as
well, but only if the sync is successful.
* Add to Argyle's **ApplicantBeganLinkingEmployer** the
`client_agency_id` for parity with other CBV flow events.
* Add to **ApplicantClickedFeedbackLink** the `cbv_applicant_id`, if
present, so the distinct_id gets set properly.
* Acceptance testing should be done by **design** for visual changes, **product** for behavior/logic …
> Add Mixpanel attributes to two events

- app/config/locales/es.yml
- app/lib/i18n_csv_tasks.rb
Resolves [FFS-3115](https://jiraent.cms.gov/browse/FFS-3115).
* Added spanish translations for LA wind-down page
* Fixed a couple issues with the import translation script
* It assumed that you were importing a file with Windows UTF-8 encodings which caused it to break. I turned that off and added a comment.
* I forced the to_yaml to write single lines instead of multi-line to reduce diffs on PR's.
* This …
> FFS-3115 LA Wind-down spanish translations

- .github/pull_request_template.md
Resolves [FFS-3169](https://jiraent.cms.gov/browse/FFS-3169).
- Update PR template
* Make sure to notify the team once this PR is merged so we don't inadvertently deploy the unaccepted change to production. (e.g. `:alert: Deploy block! @ffs-eng I just merged PR [#123] and will be doing …
> FFS-3169: Update pull request template with Terraform reminder

- app/Dockerfile
> Upgrade libxslt1-dev to address security finding

- infra/app/app-config/prod.tf
N/A - Followup from minor incident this morning.
We [learned this morning][1] that two are not sufficient to keep the
queue from growing. Let's up the count to 4 for the remainder of the LA
messaging week.
[1]: https://cmsgov.slack.com/archives/C08GB9BHSEB/p1755698014230989?thread_ts=1755696907.956919&cid=C08GB9BHSEB …
> Increase solidqueue workers 2 -> 4 for LA launch week

- .github/reviewer-lottery.yml
> No ticket: update reviewer lottery

- app/config/locales/en.yml
- app/config/locales/es.yml
1. A ticket copied an error banner to /summary but did not copy two strings that it required. These strings have now been copied.
2. There were three strings that were no longer used at all. These have been deleted.
This made it into main because:
1. The copied strings were missing in both en and es, so the bespoke action did not catch them
2. The i18n-tasks health action is incorrectly testing main, not the pr, so it did not catch them
I am taking on work to fix this GHA so this does not happen again, but that is not happening in this PR.
* Acceptance …
> No ticket: fix translations in main

- infra/app/app-config/prod.tf
Resolves [FFS-3298](https://jiraent.cms.gov/browse/FFS-3298).
Reduce containers & database back to standard
* Make sure to notify the team once this PR is merged so we don't inadvertently deploy the unaccepted change to production. (e.g. `:alert: Deploy block! @ffs-eng I just merged PR [#123] …
> FFS-3298: Return containers and database to standard configuration 💵 

- infra/app/app-config/env-config/database.tf
- infra/app/app-config/env-config/variables.tf
- infra/app/app-config/prod.tf
- infra/app/database/main.tf
- infra/modules/database/backups.tf
- infra/modules/database/main.tf
- infra/modules/database/variables.tf
Resolves [FFS-3209](https://jiraent.cms.gov/browse/FFS-3209).
- AWS Backup from 21 to 14 days, disabled for dev
- AWS Aurora RDS retention period from 1 -> 7 for prod, 0 for dev …
> FFS-3209: Reconfigure database backups

- app/app/components/aggregate_data_point_component.rb
- app/app/helpers/report_view_helper.rb
- app/app/services/client_agency/la_ldh/report_fields.rb
- app/spec/helpers/report_view_helper_spec.rb
Part of [FFS-3369](https://jiraent.cms.gov/browse/FFS-3369).
Although this seems a bit pointless, perhaps, this method coalesces a
blank string into "N/A" - a common pattern within the report.
* Make sure to notify the team once this PR is merged so we don't inadvertently deploy the …
> Create `format_string` helper to coalesce report fields to "N/A"

- app/.env
- app/config/client-agency-config.yml
- infra/app/app-config/env-config/environment-variables.tf
Resolves [FFS-3384](https://jiraent.cms.gov/browse/FFS-3384).
* Make sure to notify the team once this PR is merged so we don't inadvertently deploy the unaccepted change to production. (e.g. `:alert: Deploy block! @ffs-eng I just merged PR [#123] and will be doing acceptance testing in demo …
> FFS-3384: Add configuration for LA LDH Income Report API

- app/Dockerfile
> Fix CVE-2025-9230 by upgrading openssl

- app/app/assets/stylesheets/cbv.scss
- app/app/components/accordion_component.html.erb
- app/app/views/cbv/entries/show.html.erb
- app/config/locales/en.yml
- app/config/locales/es.yml
- app/spec/e2e/cbv_flow_pinwheel_spec.rb
- app/spec/e2e/cbv_flow_spec.rb
Several updates to /entry, including:
* Updates to the checkbox copy
* New "Common questions" header
* Two new accordions, "what is "report my income"" and "is my data secure" …
> FFS-3387: /entry improvements

- app/app/views/pages/_la_ldh_pilot_end.html.erb
- app/config/locales/en.yml
- app/config/locales/es.yml
N/A - Noticed during local testing.
This value is missing after a91b786f removed the email-based
transmission method. Since it is a public email that's unlikely to
change, I've just hardcoded it here.
Before:
After: …
> Hardcode LA LDH email on pilot-ended page

- app/config/newrelic.yml
N/A
Dev is for the previously-named "demo" environment hosted in AWS.
Not to be confused with "Development" which is local.
I will deploy this by setting NEW_RELIC_ENV=dev in our newly-renamed dev
environment.
* Make sure to notify the team once this PR is merged so we don't inadvertently …
> Add NewRelic environment for "dev" to differentiate from "demo"
